const proza = [
  { 
      nazev: 'Zajdem na pivo.', 
      text: `Skončila mi směna a já už dobrou hodinu seděl na baru v prázdné kavárně se ztlumenými světly. Neměl jsem důvod ke spěchu. Byla sobota a na ves, kde jsem tou dobou bydlel, jezdily večerní autobusy jednou za dvě hodiny. 
Nevím proč, ale lidi měli ve zvyku chodit do kavárny pět minut před koncem otevírací doby a zároveň si při tom zvykli vyžadovat velký a složitý objednávky. Irská káva, tenhle dort a támhleten malinovej košíček, navrch limonádu, japonský sypaný čaj a dvojité espresso. Rezignoval jsem na hádky a rezignoval jsem na dřívější autobus. Měl jsem hlad, potřeboval jsem na záchod, v kavárně byl bordel a domů se mi stejně zas tolik nechtělo. Nechtěl jsem rezignovat na sebe. 
A tak jsem si seděl na baru, četl noviny a dojídal studené zbytky od oběda. Bylo šest, venku tma a první dubnový týden se chýlil ke konci. Podíval jsem se na datum. Dnes večer se v městské hale konal galavečer MMA. Holka byla pryč a já nechtěl sám zevlit po barech. Nechtělo se mi zevlit vůbec nikde, kde se nic neděje a kde bych mohl začít přemýšlet nad tím, jak zoufalá moje situace je. Zvedl jsem se ze židle a rozhodl se jít. Kdybych měl štěstí, dorazil bych na část prvního zápasu, já ale štěstí moc nemíval a první zápasy stejně nikoho nezajímaly. Včetně mě.
Když jsem se oblékal, periferně jsem zahlédl, jak se před výlohou zastavil člověk. Nebylo nic zvláštního, že se sem tam někdo pokoušel vejít i hodinu po zavíračce, když viděl, že se v kavárně něco děje. Vlastně to ti pitomci zkoušeli i když se v ní nic nedělo, ať už bylo, nebo nebylo otevřeno. Není nad to si dát svoje oblíbené ovesné latté v šest večer. Otočil jsem se směrem ven, s úmyslem poslat toho šťastlive do hajzlu, místo toho jsem ale uviděl nejmladšího zastupitele města a shodou okolností mého kamaráda. Adam na sobě měl šedý oblek s vestičkou, rozepnutý kabát za dobrých deset tisíc a řádně naleštěné boty v černé kůži. Vítr mu rozháněl blonďatou čupřinu a pod nosem se mu chvělo pět tlustých bledých fousků. Odemkl jsem dveře, pozdravili jsme se. 
„Nejdeš na pivo?“ koukal na mě psíma očima. 
„Pivo si můžeme dát i na zápasech.“ 
„Na zápasech?“
„V aréně se dneska bude zápasit o pás těžký váhy. A pivo tam teda taky čepujou. Buď tam a nebo nikde,“ byl jsem nekompromisní. 
Vypadal, že ho zmínka o zápasech trochu zaskočila. Musel přemýšlet nad tím, jestli je zrovna taková společenská událost vhodná a jestli mu nemůže poškodit jeho politickou pověst. 
„Tak fajn,“ řekl po chvíli civění do prázdna. A šli jsme. 
Zaplatil nám lístky přímo na plochu, k nástupové uličce. Já chtěl vidět a on chtěl být viděn. Byl to přece jenom politik. A já byl přece jenom blbej divák. Cestou na místa jsme koupili to slíbený pivo. Člověk by v něm našel všechny barvy na škále od zelené po černou. Podle toho taky chutnalo. Nejspíš v tom kelímku bylo víc vody než piva a dost možná v něm bylo víc kelímku než piva, když si ale člověk koupí pivo, pije pivo, konec debaty. 
Cestou k našim místům se Adam pozdravil s podobně vypadajícími typy. Vypadal, že je poněkud v rozpacích, když si podával s lidmi ruce. Dosedli jsme právě ve chvíli, kdy začínal třetí zápas a dle naladění publika jsme o nic moc nepřišli. Hala byla zatím zaplněná sotva z poloviny. 
„Tak co tě žere?“ zeptal jsem se Adama, který se na židli vrtěl a hledal pohodlnou a zároveň reprezentativní polohu, ve které by mohl vydržet několik následujících hodin. Vypadal jako by zahříval vajíčka. Možná že to tak i ve skutečnosti bylo. Rozepnul si sako a já sledoval, jak kolem sebe v kleci krouží dva sotva dvacetiletí kluci. Byl jsem rád, že sedím tam kde sedím, a že oni jsou tam kde jsou. Zkrátka jsem byl rád, že to není naopak. 
„Na zastupitelstvu zrovna řešíme, jestli na městským pozemku postavit novou školku a nebo dům pro seniory. Když se rozhodneme pro důchoďák, opozice si začne hrát na milovníky dětí, když pro školku, však víš…“ 
„To se přece nevylučuje,“ upil jsem z kelímku. 
„To asi ne…“ Zrovna když mi chtěl začít vysvětlovat složitou problematiku rozložení sil v místním zastupitelstvu, vzal jeden bojovník toho druhého a praštil s ním o zem tak, že si oba na chvíli vyrazili dech. V hale to zlehka zabouřilo. Taky Adam pokyvoval hlavou. 
„Neříkej mi, že máš v hlavě jenom stavbu jednoho posranýho baráku,“ pokračoval  jsem, když se situace na zemi trochu uklidnila, do konce kola zbývaly tři minuty a frajer ve vrchní pozici kontroloval protivníka pod sebou.
„Ale to ne,“ utrousil Adam. Napil se a zkřivil přitom obličej, jako opozičník při pohledu na plán nové školky pro důchodce. 
„Je v tom holka?“
„Jistěže.“
„Já ani nevěděl, že nějakou máš.“
„Skončilo to dřív, než to začalo.“ 
„Musíš jít dál, jinak tě její pozůstalost sežere zevnitř.“
„To se snadno řekne“
„Před dvěma rokama jsem byl s jednou, co mi doteď volá.“
„Jako k narozeninám a na Novej rok?“
„Spíš uprostřed bezvýznamnýho a klidnýho večera.“
„Chce tě zpátky?“
„Připomíná mi, jak fajn by bylo, kdybych se zabil. Prý bych tím prospěl jí, svýmu okolí a sobě.“
„Tak to jsem na tom ještě celkem dobře. Mě prostě ignoruje.“
„To jsi. “
První kolo skončilo a v modrém i červeném rohu probíhala porada. Hala se konečně zaplnila. Dopil jsem pivo a vzal jsem do ruky turnajovou kartu, kde byly vypsány všechny zápasy. 
„Hele, bude tu pár hratelných zápasů. Nechceš si vsadit?“
„Já nevím…“ 
„Štěstí začátečníka. Stačí když ukážeš prstem a vyjde ti to. Poprvý to vždycky vyjde.“
Adam se mi nahnul přes rameno a podíval se na rozpis. Náhodně zabořil prst na jméno borce, na kterého byl vypsaný kurz šest ku jedné. Já se pousmál. Skoro bych vzal svojí předešlou poznámku o štěstí začátečníka zpátky, tenhle neměl šanci. Byl to osmatřicetiletý Brazilec Silva. Se sto padesáti centimetry měl na kontě 9-6. Nastupoval proti vycházející hvězdě, dvoumetrovému migrantovi z východu, který byl místními považován za domácího. Celou svou profesionální kariéru totiž odzápasil v téhle zemi. Občas organizace přivezla zápasníky z Brazílie, Balkánu nebo z Ukrajiny, kterým zaplatila minimální plat. Ten byl ale stále výrazně vyšší, než jaký by ti nešťastníci dostali doma. Tihle bojovníci nemívali na první pohled nejhorší zápasové skóre, ale buď byli staří, dva roky neaktivní, zranění, nebo před tím ještě nikdy nestáli proti pořádnému protivníkovi. Silva vypadal jako slušný boxer, ale podle všeho neměl šanci dojít byť jen do druhého kola. Rozhodl jsem, že vsadím proti němu, v kombinaci s koncem zápasu v prvním kole. 
„Nebudu ti to vymlouvat.“
„Mně se líbí, je to podsaditej frajer, toho ten druhej jen tak nehodí,“ prohlásil znalecky Adam, když si pročetl parametry obou bojovníků. 
Koukáním do karty jsme úplně prošvihli zbylý průběh zápasu. Zápasník, co v prvním kole dominoval, právě dostal přímku a hák na odkrytou bradu a skácel se k zemi. Jásot haly nás vytrhl z dumání a my jsme se na celou akci museli podívat až ze zpětného záznamu.
Rozhodl jsem se, že dneska vyhraju balík. Silva nastupoval v následujícím zápase, tak jsem si i s jednou funkční nohou trochu pospíšil ke stánku sázkové společnosti. V jedné ruce jsem měl tisícovku od Adama a sám jsem si hodlal vsadit za dvě stovky. Na malý kurzy se nevyplatilo dávat závratný sumy. Vlastně se to nevyplatilo s žádnými kurzy. 
Když jsem se vrátil na naše místa, zrovna kolem procházel ten nadějnej mládenec z východu. Adam si ho moc nevšímal a dělal si v turnajové kartě kroužky u dalších jmen. Prošel si všechny zbylé zápasy. Seděl na židli s nohou přes nohu, až mu čouhal kus oholeného lýtka nad ponožkou. Už vůbec nevypadal tak reprezentativně, vajíčka si ale hřál pořád. 
„Tak koukám že jsi na ní rychle zapomněl.“
„Tohle je totiž hodně návyková zábava.“
„To ještě nic nezačalo. A mluv ty vole jako normální člověk.“ Oba jsme se usmáli. Zápas začal. 
Čekal jsem, že kolem sebe budou chvíli kroužit a to dvoumetrový hovado se brzo pokusí vzít celou věc na zem. Jeho styl vycházel z Dagestánského wrestlingu, jak si i Adam přečetl na kartě. On sice na rozdíl ode mě možná věděl, kde leží Dagestán, já ale zase věděl, jak nebezpečnej tenhle frajer umí být. Jenže kolem sebe ti dva tupci kroužili už druhou minutu a vyjma dvou kopů se nic zásadního neodehrálo. Najednou do toho ale wrestler vlítnul. S rukama před sebou hodil šipku po nohách Silvy. Ten vyslal levý hák ze zadní. Až v ten moment jsem si všiml, že je Brazilec levák. Nejspíš si to v tu samou chvíli uvědomil i jeho protivník, protože rána dopadla na odhalený spánek a s domestikovaným Dagestáncem otřásla. Pokusil se vycouvat, ale díky svým dvěma metrům stihl inkasovat ještě dva rychlé spodky, které jakž takž ustál. Kroužení pokračovalo, ale vítěz první výměny byl jasný. Adam se na mě významně podíval a já začínal být lehce nervózní. Bylo by mi i docela jedno, kdo z těch dvou vyhraje, kdybych neměl vsazeno. 
Konečně přišel druhý pokus o vzetí na zem. Oba borci se chvíli pasovali uprostřed klece, ale vypadalo to, že Silvu není za co chytit. Adam měl pravdu, opravdu to byl podsaditej frajer, kterýho jen tak nehodíš. Skoro neměl krk, a obvod jeho stehen byl tak velkej, že se mi vybavily vzpomínky na babičku. Přišel třetí pokus o takedown, jenže Dagestánec při nástupu kopl samotný Lowkick a Silva ihned správně kontroval zadní rukou. Dlouhán šel do kolen a Brazilec mu začal sázet jedno kladívko za druhým. Než se rozhodčí vzpamatoval a zakročil, dopadlo jich šest, možná osm. Trvalo ještě několik dalších vteřin, než jsem se vzpamatoval i já, Adam, celá hala, promotéři, uklízečka, bezdomovci na parkovišti před halou, bezdomovci na parkovišti za halou a kanálové krysy.
Adam vyskočil na nohy, až se mu z toho rozhodila uspořádaná pěšinka. Měl pětku v kapse a já měl velký hovno. 
„Vidíš, já to říkal.“
„Tvoje dny jsou sečtený kamaráde, dvakrát začátečníka štěstí nikdy nepotká.“
„Na, tady máš tiket a zápasovou kartu. Vsaď mi prosím po stovce na zakroužkovanýho vítěze, za zbytek si vsaď ty.“ 
„No tak fajn. Dík,“ podal mi kartu a já na ní letmo pohlédl. Adam se úplně pomátl. Sázel ty nejvyšší kurzy, na vítěze, na vítěze a způsob výhry a na vítěze a kolo předčasného ukončení. Chtěl jsem se ho zeptat, jestli je na zápasech poprvé, jak říkal, ale pak mi došlo, že podle těch tipů opravdu musí být. Na první pohled vypadaly hrozně, na druhej opravdu byly a na třetí pohled to byly prostě jenom střely od boku. Nic jsem mu ale nevymlouval, mohl jsem vsadit za část jeho výhry a to mi stačilo Byl jsem sám jenom úplatná kanálová krysa. Navíc jsem moc dobře věděl, že sázky jsou loterie. Padesát na padesát, pokud ponechám stranou sázky na způsob a čas konce zápasu. Stejný jako umění vyhrávat bylo i umění prohrávat. Systém si vás držel u těla tak akorát. Nechal vás sázet, nevyhrát a ani neprohrát moc. Jednoduchý. Maminko, až budu velký, otevřu si sázkovou kancelář, říkal jsem si v pauze mezi předzápasy a hlavní kartou, když jsem kroužkoval svoje vlastní tipy a vyrazil jsem vsadit. 
Adam se šel vymočit a já ho posléze následoval. Na záchodech byl jako tradičně hroznej bordel, až moc dlouhá fronta a příšernej smrad. Cestou zpět jsem vzal další dvě piva. 
Proběhlo dalších několik zápasů a nebyl jsem na tom o moc líp, zato Adamovi karta šla. Kde já vsadil na bodové rozhodnutí, on vsázel KO a když já vsadil na outsidera, on vyhrál s favoritem. Užíval jsem si zápasy a užíval jsem si taky to, že si je užíval Adam. Bylo na něm vidět, že pookřál, zmizely mu kruhy pod očima a nejspíš ta celá akce fungovala i jako prevence proti rakovině plic a hemeroidům. Když se nastupovalo k ženskému zápasu, vedle chlupů pod nosem mu dost možná stálo i něco dalšího. 
Ten ženský zápas vyrazil dech celý aréně. Byla to tříkolová bitva a do poslední minuty nebylo jasný, kdo si to z těch holek urve pro sebe. 
„PODÍVEJ SE NA TO! Vždyť takový tempo nemůžou VYDRŽET!“ křičel mi do ucha Adam. 
„TO VÍŠ ŽE MŮŽOU!“ křičel jsem zpátky, aniž bych odtrhl oči od klece.
Nakonec vyhrála Polská bojovnice a s úsměvem na obličeji plném barev, modřin tržných ranek a podlitin opouštěla klec. 
„Představ si, že je to tvoje máma, nebo dcera, nebo stará,“ říkal mi Adam, když si uvědomil, že prohrál první sázku. 
„Já nemám dceru, teda alespoň doufám, ale kdyby tam stála moje bejvalá, tak by mi to asi nevadilo,“ utrousil jsem a bral jsem první výhru. Polka byla zkušenější, dalo se čekat, že vyhraje, nedalo se ale čekat, že tak těsně a po takové rvačce. Slabej kurz, slabá útěcha. 
Hřebem večera měl být zápas o titul těžké váhy. Pás držel Angličan s kontem 21-2. Obě jeho prohry byly diskvalifikační. Obecně zápasil jakoby mu nikdo nikdy neřekl pravidla, ale fungovalo to. Nastupoval proti němu Němec původem z Gruzie. Ve druhé minutě prvního kola byl konec a Německého Gruzince museli čtyři chlapy odnášet na nosítkách. Byla to rychlá tečka za celým večerem, ale já s kurzem čtyři ku jedné na ukončení via KO dorovnal všechny předchozí ztráty. Svět byl v rovnováze. 
Domluvili jsme se s Adamem, že budeme chodit pravidelně, jednou za měsíc, kdy se turnaje konali. Odešel jsem na vlak a po dlouhý době jsem měl dobrej pocit z toho, že jsem pro druhýho člověka doopravdy něco dobrýho udělal.  
A tak jsme pravidelně chodili na turnaje a taky jsme sázeli. Bylo to hlavně o tom odhadnout, kdy se v zápase jednalo o zjevné budování domácích a kdy to měla být opravdová a vyrovnaná výzva. Adam sázel stále stejně nesmyslně se střídavou úspěšností. Propadl tomu opravdu rychle, ale šlo mu o hru, né o výhru. Na turnaje taky vždycky chodil ve svém obleku a turnaj od turnaje se mi zdál veselejší. Během jednoho letního turnaje, který se konal pod otevřeným nebem se během pěti hodin dokázal tak zlít, že jsem ho cestou k taxíku musel podpírat. Nevadilo mi to. Něco se kolem mě konečně začalo dít. 
Proběhla další řada galavečerů a já dál pracoval v té stejné kavárně, za ty stejné mizerné peníze, ostatně dost odpovídající té mizerné práci. Šéfová byla pořád stejně mizerná a rodila další mizerný parchanty. Její mateřská nebrala konce. 
Adam se dostal do parlamentu a musel se přestěhovat do Prahy. Pak vznikla nová vláda a on zasedl jako nejmladší ministr v historii země. Nikdy jsem se o jeho politickou činnost nezajímal. Politika mě totiž začala zajímat moc brzo na to, abych se jí mohl aktivně účastnit. Ve chvíli, kdy už jsem někam teoreticky kandidovat mohl, ztratil jsem chuť diskutovat, nechtěl jsem sdílet svoje přesvědčení a zajímat se o přesvědčení ostatních se mi vyloženě hnusilo. Uvědomil jsem si, že z aktivní angažovanosti číhá tak maximálně obrovskej průser a v horším případě úspěch a zářná politická kariéra. PR oddělení ministerstva mu nedoporučilo účast na podobných akcích a tak mi prostě jednoho dne zavolal jeho tajemník, aby mi sdělil, že si musím najít někoho jiného. Už jsem se mu totiž v tu dobu ani nebyl schopný dovolat a přes ochranku kolem jeho domu taky nikdo jako já neprošel. 
No a tak jsem chodil sám. Pořád bez obleku, jenom jsem si nesedal k nástupové uličce, ale někam vysoko do hlediště. A taky jsem sázel za svoje, což reálně znamenalo, že jsem nad tím začal ještě více přemýšlet a sázel jsem za menší. Výsledky ale byly stejný, možná ještě o něco horší než předtím. Ale ani mně nešlo tolik o výhru, jako o hru, pokud to teda zrovna nebylo naopak. 
Uběhlo několik let, až se jednoho dubnového dne objevila ve všech novinách zpráva o skandálu politických špiček. Místo novely zákona o představování nových novel zákona tak musel Adam vysvětlovat dětskou pornografii nalezenou uklízečkou v jeho ministerské kanceláři. Nikdo z veřejnosti ale neuvěřil verzi, že uklízečku podplatila opozice, aby mu to porno do kanceláře sama nastražila. Byl donucen rezignovat a rozhodl se opustit politiku. Televizi ani veřejné dění jsem moc nesledoval. Nedělalo mi dobře, ale v jeho případě jsem udělal vyjímku. Kauza byla po týdnu propírání ze všech stran vyčerpána a jelo se dál. 
Skončila mi směna a já docela spěchal. Mopem jsem nakonec úklidu ještě vytíral podlahu kavárny, když na sklo výlohy zaklepal Adam. Nejdřív jsem ho nepoznal, ale byl to on. Stál tam ve svetru a sepraných džínách, na hlavě měl naraženou čepici, pod nosem šest fousků a tři další na bradě. Trochu neohrabaně zaboxoval do vzduchu, napil se vzdušného půllitru a natočil hlavu. Pochopil jsem otázku. 
„Nezajdem na pivo?“` 
    },
    { 
      nazev: 'Jdeš spát, jdu psát.', 
      text: `Vykoukl jsem zpoza dveří. Na chodbičce byla tma, v bytě ticho, někdy mezi desátou a šestou, každopádně ideální čas. V kuchyni jsem rozsvítil světlo nad dřezem a do poloprázdné skleničky jsem si dotočil vodu. Na linku vyskočil kocour. Nejspíš se kolem mě procházel celou tu dobu. Byl to černej kocour a tak měl celkem štěstí, že jsem o něj nezakopl. Možná to štěstí bylo spíš na mojí straně, jemu to mohlo být docela jedno. Nesměl na tu linku vyskakovat a moc dobře to věděl. Přesto si vyskakoval a já neměl v plánu mu to kazit. Podíval se na mě svýma žlutýma očima. „Mrrr,“ vypustil ze sebe. „Mrrr,“ vrátil jsem mu to a napil jsem se vody. Když jsem se natahoval po vypínači, ohnal se po mě a zakousl se mi do ruky, načež hned ucukl a než jsem mu to stihl vrátit, zmizel ve tmě. Nad kočkou nikdy nemůžete zvítězit. 
Vrátil jsem se do pokoje a teď tu sedím u okna a venku prší. Starý dům a staré praskající topení zní ze všech stran a ze všech stěn. Zní to, jako by to tu mělo každou chvíli explodovat. Ale přesto tu sedím a zatím jsem se taky dožil každého rána po každé noci, kterou jsem tu strávil. Doufám, že to bude zdárně pokračovat i nadále. Na posteli spí jedno kouzelná stvoření, co se usmívá i ve spánku. Vykouřila mě a usla, jakoby nic. A já tu teď sedím u stolu, a u okna, a u počítače, a potichu do něj klepu věty. Jakoby nic. Teď další. A další. 
Trochu mě vyděsila představa, že tenhle PC-parchant zná každej můj překlep. Každou myšlenku, kterou jsem si rozmyslel a vzal zpět. Né že by jich bylo zase tolik, ale těch překlepů už bude o něco víc. Musí si o mně myslet, že jsem naprostý hovado a úplnej debil. Ale aby mi poradil, co mám se sebou dělat, to ne. Miluju tyhle tichý intelektuály, co mají na všechno odpověď, ale opraví vás jenom ve chvíli, kdy se vůbec na nic neptáte. A SERU TI NA AKTUALIZACI TY KRETÉNE! 
Nemám ponětí jaká má být myšlenka tohohle textu. Ale tak je to ostatně s každým obdobným večerním psaním, který praktikuju tak jednou za čtvrt roku, buď na začátku a nebo na konci mojí psací štace. Doufám jenom, že to v následujících dnech bude stát za to. 
Za dva týdny je konečně další turnaj. Procházel jsem kurzy, ale stojí to za nic. Domácí mají nevsaditelnej kurz a radši než abych sázel proti nim, dám ty peníze do loterie. Prohraju a předem si tím budu jistej v obou případech. Ale i tak se na to těším. Podobný události mi vždycky dají pár podnětů psát. Zrovna teď mám rozepsaný dvě povídky o zcela evidentně fiktivních bojovnících, jejichž příběhy jsou stejně tak zcela evidentně smyšlený. Jenom pro ty povídky hledám název. Baví mě psát a nebrat se při tom moc vážně, nebrat při tom vážně vůbec nic. Jednou větou stereotyp bourat a v druhý větě ho zastávat. Někdy se rozmýšlím, jestli určitou pasáž napsat a pak si prostě řeknu: „Jasně že to napíšu, no proč bych sakra nemoh, je to můj text kurvafix.“ Tuším, že ve mně tohle pochybování vyrostlo ještě za dítěte, a já jsem rád, že ze mě psaní dělá znovu puberťáka.
 Jsem obecně rád, co ze mě psaní dělá a co já dělám se psaním. Můžu si svobodně třeba i protiřečit a nikdo s tím neudělá ani prd. Všichni jsou moc vážní a zaujatí sami sebou, svým vlastním světem, svou vlastní hlavou. Když má okolí moc velkej vliv na člověka, stane se z něj jeho vlastní okolí. A mě nezajímají ani lidi, ani jejich okolí, a ani moje okolí. Když mi to všechno začne moc vrtat v hlavě, vymlátím to ven bušením do písmenek na klávesnici. Je po boji, svět je v rovnováze, všichni mají všechno a nikdo nemá nic. No a co nemáš, nepotřebuješ. Já třeba už nepotřebuju pokračovat v tomhle textu. Konec.` 
    },
    { 
      nazev: 'Zápasový trable.', 
      text: `Bylo pozdní ráno. Marek vyšel na terasu a rukou se opřel o zděné zábradlí. Podíval se na panorama hor a viděl, jak se mlha trhá na kusy o špičky smrků. Pohladil chrliče po hlavě. Dneska by to šlo, říkal si a v kapse županu mu začal zvonit telefon. 
Včerejšek si Marek užil bez manželky, dětí, zaměstnanců, reklamních emailů, reklamních poutačů, firemních emailů, firemních meetingů, psů, koček, nutnosti vynést koš, nutnosti dělat cokoliv a hlavně bez toho, aby mu volal jedinej manažer nebo zápasník s nějakou prosbou, podmínkou, návrhem nebo jinou píčovinou. Dovolená skončila. Vytáhl telefon z kapsy, mírně se rozkročil a na koulích ucítil jemný závan horského vánku. 
„Haló?“ 
„Nazdar, tady Ted. Hele, je to sice blbý, ale nedá se nic dělat. Bill si při posledním tréninku utrhl křížovej vaz v koleni a nemůže do toho zápasu nastoupit.“ 
V Markovi hrklo. Místo hor a vánku teď cítil studený pot a před sebou viděl mizící miliony za vstupné a davy nasraných diváků. Nebylo to poprvý, co se před očekávaným zápasem někdo zranil, tentokrát to ale bylo jiný. Žebříčku těžké váhy kraloval Bill „The Hangover“ Taylor už dlouhé roky. Taylor byl navíc ve skutečnosti jediný zápasník těžké váhy, se kterým měla organizace uzavřený dlouhodobý kontrakt. Všechny ostatní zápasníky by organizace na dlouhodobý kontrakt podepsala jenom v případě, že by s Taylorem předvedli alespoň vyrovnaný výkon. Jenomže to se zatím nikomu nepodařilo. S každým koho mu předhodili vytřel Taylor podlahu a i když se o něm tak nějak všeobecně vědělo, že před i po zápasech chlastá jako duha, stejně se z něj časem stal miláček publika. Marek měl dokonce podezření, že Bill chlastá i během zápasů, nebo na něj občas alespoň tak působil. Ale nijak to neprošetřoval. nakonec to byla jeho zápasová organizace a mohl si s ní dělat, co chtěl. 
Možná to bylo právě díky chlastu, možná jeho těžkým dětstvím, každopádně byl během půl roku Bill schopný vyhrát v organizaci tři zápasy a na konci téhle štace si došel i pro titul. Prozatimní šampion padl k zemi v druhém kole a čekala ho projížďka rychlou na místní kliniku. Po tom už nikdy nenastoupil do klece. Naopak Taylor si během následujících čtyř let připsal osm výher a tak se z něj stal i nejlépe placený zápasník organizace. Byl to excelentní boxer a i když měl bachor, za který by se nestyděl průměrný obývákový povaleč, s jemu hodnou ladností poskakoval dokola a kroužil kolem svých soupeřů, dokud nevyrazil a nevystřelil je z trenek. Jeho slabost spočívala v boji na zemi. Bill byl ale opravdu TĚŽKÁ těžká váha a na zem ho jen tak někdo nedostal. 
Před nedávnem si o něj ale řekl šampion polotěžké váhy, Francouz Montagnac. Ve skutečnosti to teda nebyl úplně rodilý Francouz. Když mu byly dva roky, připlul do Francie v nějaký nákladní lodi z Alžírska. Vzhledem k jeho barvě pleti to musela být nejspíš loď s uhlím. Je ale možný, že se na něm podepsala genetika. Každopádně byl Montagnac neskutečný zvíře. Poslal do důchodu několik domácích veteránů a v každém zápase působil větší a větší. Před posledním zápasem, kdy po pětikolové bitvě urval titul, měl velké problémy s váhou. Nakonec ji ale splnil a ihned po výhře ohlásil přestup do vyšší váhovky. Jelikož Francouz docela nasral domácí fanoušky, přáli si ho vidět padnout ve velkým stylu a Marek chtěl zase nový auto, takže bylo rozhodnuto. Zápas měl svoje datum a hala byla týden před turnajem vyprodaná. Lokální noviny mluvili o nové stoleté válce, bulvár zase o šikaně přistěhovalců. Mělo to všechno. Bill zesměšňoval na sociálních sítích svého soupeře, zatímco Montagnac posílal videovzkazy, kterým nikdo nerozuměl a organizace neměla prachy na překladatele. Ty vzkazy ale zněly opravdu nasraně a budily respekt. Zranění Taylora ale do všeho hodilo vidle. 
Marek položil telefon, sundal si župan a vlezl do vířivky, která stála na terase. Otevřel si zbytek lahve koňaku. Věděl, že Francouz si soupeře nevybírá, ale kde měl týden před zápasem sehnat někoho, kdo se alespoň na první pohled nebude zdát jako úplná potrava? Volal známému manažerovi brazilských zápasníků. Brazilců je hodně, vždycky se nějakej volnej najde, říkal si v duchu Marek, když mu v uchu znělo vytáčení, které ho opravdu vytáčelo. Manažer to zvedl a navrhl několik podřadných jmen. Silva, Silva, Silva, Santos, Rodrigues, Gomez, Lopez. Markovi šla ze jmen hlava kolem a z jejich zápasových skóre ještě víc. 3-8, 2-5, 0-0, 0-2, 1-1, 4-54, 1-9. Manažer nakonec nabídl dalšího Silvu, třicetiletého zápasníka s kontem 7-5. Konečně někdo, kdo konto neměl záporné. Tenhle Silva navíc zápasil poměrně pravidelně a se svými 193 centimetry působil vcelku obstojně. Stačilo ho představit jako dítě slumu a bývalého drogového dealera, který se sportem vypracoval až do Evropy. Proti neporaženému Montagnacovi s pěti výhrami v řadě navíc nepůsobil jako naprostá dávačka. Marek bez rozmýšlení nabídl podepsání kontraktu s 1000 eury za zápas. Brazilský manažer ale nesouhlasil a žádal pět tisíc. Marek se s ním chvíli dohadoval, ale když byl Brazilec neoblomný, se slovy „Strč si všechny svoje Silvy do prdele!“ zavěsil a mrštil telefonem do druhého rohu vířivky. Telefon se potopil, zablikal a zhasnul. 
Marek se stále nedobitou lahví koňaku v ruce vylezl z vířivky. Stále ještě nahý zašel na pokoj a zavřel za sebou skleněné posuvné dveře. Popadl notýsek v koženém přebalu, který se válel na nočním stolku. Začal listovat. Hledal kontakty na zápasníky těžké a polotěžké váhy. Jedno našel. Grzegorz Przeczek byl Polák s kontem 12-13. Bylo mu jednačtyřicet, ale pořád se toho nebál. Naposled před rokem utahal začínajícího Slováka s rekordem 0-1. Marek s nadějí v očích položil lahev koňaku a na hotelovém telefonu vytočil polákovo číslo. Možná neměl pozitivní zápasové skóre, ale zato měl hodně zápasů. 
	Zvedl to jakýsi advokát.
„Pan Przeczek nemůže v tuhle chvíli nastoupit do zápasu. Načapal při nevěře svou pátou manželku.“ 
„Zabil snad někoho?”
„To ani ne. Ta paní byla s jiným polským zápasníkem, místním šampionem s kontem 24-2. Když to na něj Przeczek vybalil, dostal sám přes držku a manželka nato podala žádost o rozvod. Teď leží v nemocnici a vypadá to, že si ještě nějakou dobu poleží.“ 
„Tak ho ode mě pozdravujte a dejte vědět, až se bude moct postavit na nohy.”
	Marek prásknul telefonem o noční stolek a koulil oči. Nápady mu docházeli skoro stejně rychle jako trpělivost. Po dvaceti minutách listování v intenzivně popsaném zápisníku narazil na číslo jistého Němce, který měl rekord 3-2. Zkusil to, ale nikdo mu to nezvedl. Na poslední stránce notýsku bylo napsané jméno Chorvata. Stěží čitelné telefoní číslo naťukal do číselníku. Tenhle maník má dva metry dvacet a hrozivý rekord 4-9. I když tři roky nezápasil, byl schopnej nastoupit za jídlo, hotel a pět set na ruku. Když nastoupil naposledy, vydržel 19 vteřin, ale díky tomu, že nastoupil, vytrhl Markovi trn z paty. Dalo by se říct, že mu tu titulovou šanci dluží, čili že si jí Chorvat zaslouží. 
„V postoji je sice tragickej, zato zemař je to taky úplně na hovno.“ Říkal si Marek při zkoumání jeho zápasové historie. Co mu ale zbývalo… 
Když Marek končeně domluvil zápas, zavolal ještě marketingovému oddělení. 
„Ohlašte změnu, Bill se zranil. Do mailu pošlu údaje nového zápasníka.“ Na druhém konci drátu se ozvalo chichotání několika ženských hlasů, které v zápětí nějaký mužský hlas okřikl. 
„Ať je na tom plakátu napsaný, že je ten náš Chorvat velkej tvrďák, co to umí rozbalit na zemi, v postoji i ve vzduchu. Teda, bez toho vzduchu. A taky doplňte, že je to extrémně zajímavej zápas, na který se mají všichni těšit, ale hlavně, který chceme všichni vidět a taky napište, že je to hřeb večera a vrchol roku a že vítěz se později utká s deBillem.“ Na druhém konci drátu nastalo ticho. Po chvíli se ozvalo jen: Tak jo.
Marek položil telefon, vzal do ruky flašku a šel zpátky do vířivky. Vylovil telefon a položil ho vedle na podlahu. Ten už to nerozchodí. Ale Mára, Mára to zase nějak dokázal.` 
    },
    { 
      nazev: 'Finanční poradenství.', 
      text: `Upravila si sukni, zkontrolovala rukávy na saku a vteřinu, nebo dvě, nebo tři, koukala na svůj malý odraz v zrcadle. Byl skoro odpovídající realitě, jenže tak nějak postrádal hloubku. Zkusila se na sebe usmát, ale moc jí to nešlo. Ve skutečnosti byla oblečená v něčem, co se příliš nelišilo od uniformy, jakou právě teď někdo nosí, zatímco smaží hranolky v populárním řetězci rychlého občerstvení. Z nějakého důvodu se tomu oděvu ale v jejím případě říkalo formální společenské oblečení. Kdyby před tím zrcadlem stálo její tři měsíce staré já, těžko by se asi poznalo. Kdyby to zrcadlo mohlo mluvit, ptalo by se na tolik věcí. Kde jsi? Holko s krátkými vlasy, které mají každý týden jinou barvu? Kde jsi? Holko, co zásadně nenosíš podprsenku? Kam zmizely tvoje rozlámané vinylové desky s interprety z osmdesátých let nalepené nad postelí? Kde je tvoje touha po psaní? O jaký břeh se rozbila vlna tvojí nespoutanosti? Proč k tobě promlouvám větami, které by použil průměrný vysokoškolský lektor tvůrčího psaní? Zavřela za sebou dveře od oné místnosti a přisedla si zpátky ke klientovi. V kavárně bylo několik dalších lidí a většina z nich předstírala, že něco dělá, zbytek nevěděl, co tam dělá. 
„Tak, jsme na všem domluvení, na příští schůzku vám přinesu smlouvu a podklady k vašemu nově sjednanému investičnímu portfoliu. Mám z našeho dnešního jednání radost. Už jsem vám říkala, že situace s finanční gramotností napříč populací v naší zemi je velmi problematická. Jsem ráda, že společně napomáháme pozitivní změně. Než se rozejdeme, máte na mě ještě nějaké otázky?“ Muž ve svých pozdních dvacátých letech postrádal nejen vlasy, ale také pozornost. Vrhl na ní pohled dobytka s právě přiloženou jateční pistolí u hlavy. Jenom někdo jako on dokázal jít bez výčitek na schůzku s finanční poradkyní v teplákách. Dělalo mu taky celkem dobře, když si představoval, jak i tahle holka nasáčkovaná v saku, košili a sukni chodí srát, že i jí se tvoří ušní maz a že i jí někdo šoustá. Nemohl vědět, že už jí ve skutečnosti dlouho nikdo neohnul. Ale s tím sraním a ušním mazem se docela trefil. 
„Dobrá, děkuji vám, budu se na vás ve čtvrtek těšit.“ Prolomila stěnu mlčení a podala klientovi ruku. Držel ji o něco déle, než by se slušelo. Jeho dlaň byla vlhká a studená. 
Když muž odešel, utřela si ruce do ubrousku, který byl přiložený u nedopitého šálku kávy. Přemýšlela nad tím, kolik klientů ještě bude muset přimět k založení účtu, než si bude moct dovolit pořídit si svého vysněného psa. Chtěla letos taky ještě stihnout kurz jógy na Kostarice a její oprýskané škodovce by taky slušela nová vrstva laku. Nebo by jí samotné možná slušela nová Škodovka. Ale nešlo jí to tak, jako si na začátku představovala. Seděla na místě s výhledem z výlohy kavárny. Měla skvělý rozhled na městskou ulici pokrytou kočičími hlavami a taky dobře viděla na to, jak ty kočičí hlavy pomalu zapadají sněhem. Kolem kavárny prošel hlouček lidí a v něm zpozorovala svého bývalého přítele. Nevšiml si jí. Tak rychle jako se objevil zase rychle zmizel. Ale z její hlavy se mu nechtělo. 
Otevřely se dveře kavárny a dovnitř vešla žena ve středním věku po boku s velkým chlupatým psem. V kavárně byl vcelku klid, takže Bety i z vedlejší místnosti jasně slyšela, co žena říká. 
„Dám si cappuccino s ovesného mléka a tady pro Bohouška vodu prosím.”
Bohoušek měl zhruba sto kilo a zabíral dobrou polovinu prostoru před barem. Bety se znovu zasnila. Jak chodí po horách s batohem, co je téměř větší než ona sama. Jak si kolem ní cupitá Bohoušek. Jak je silná a nezávislá a objevuje svět, navzdory všem překážkám, které před ní postavili její bývalí partneři, její matka, učitelky ze střední školy, daňová zátěž a sezónní závislost na alkoholu. Představovala si západy slunce a krvácení na volno, meditaci na verandě a chápavého, tolerantního, inspirativního partnera s velkým zahnutým pérem. Představovala si život šťastně až do smrti a další spoustu nesmyslů. Ze snění ji vytrhlo zavření dveří. Bohoušek odešel i s ženou středního věku. Kavárna se zdála být vylidněná, i když prázdno tu zrovna taky nebylo. 
Povzdechla si a začala z kabelky vytahovat desky a podklady pro další klientku, která už teď měla zpoždění. Bety si říkala, že chce všechno zpátky. Nevěděla, co v té kavárně vlastně dělá. Vůbec tu nechtěla být. Vůbec tu neměla být. Ale kde chtěla a měla být, na to už odmítala myslet. Život jde dál. 
Dveře do kavárny sebou trhly. Zhruba dvacetiletá dívka šla ihned k stolu, kde Bety seděla. Vyměnili si úsměvy. 
„Ahoj Bety!“ 
„Ahoj Julie!“ 
Bety už ani nepředstírala, že jí zajímá život Julie. Chtěla být co nejdřív pryč. Chtěla mít co nejdřív Bohouška. Chtěla všechno, ale jen né nové investiční portfolio. Podala Julii štos papírů.
“Situace s finanční gramotností napříč populací je v naší republice velmi problematická...“` 
    },
    { 
      nazev: 'Je to fuk.', 
      text: `Jsou dvě nebo tři nebo čtyři. Možná je půl dvanáctý a nebo taky ne. Nemám ponětí. A je mi to fuk. Minulost mě nezná a já zas nevím, co teď k sakru jako přijde. Venku navzdory předpovědím padá sníh. Ráno si ve zprávách přečtu, koho všeho včetně silničářů zaskočil, kolik spojů nevyjelo a kdo se kde vyboural. Ještě že vstanu dost pozdě na to, aby ten sníh stihl zmizet. Říkají tomu globální oteplování nebo změna klimatu. Já tomu říkám první dobrej nápad od vyhubení dinosaurů. Kroutím se jako v grotesce, rozvalenej na křesle, který má to nejlepší už za sebou. Celý pravý opěradlo je roztrhaný od psa, zbytek stojí za nic docela podobně. Z drobečků který zapadaly do jeho švů by se dala vykrmit jedna vietnamská vesnice a z toho co jsem v něm sepsal by se nenažral vůbec nikdo. 
Zavřeli mi půlku rodiny. Alespoň má, na rozdíl od tý druhý půlky, kde bydlet. Ale ve škole nám říkali, že když na sobě budeš tvrdě pracovat, dobře se učit, znát odmocninu z pěti a budeš se zájmem poslouchat historky tvojí učitelky, šéfový, nebo kohokoliv, od koho zrovna něco potřebuješ a budeš k tomu hodně snít a hezky prosit a děkovat, dokážeš cokoliv. To znamená, že nic není nemožný a vždycky jde hledat prostor pro zlepšení. 
Občas se před někým, kdo mě nezná, zmíním o tom, jak by bylo fajn žít v roubence uprostřed lesa. Měl bych tam vlastní zahrádku plnou mrkví, brambor a rajčat. V létě bych snídal hrášek a rybíz, pekl bych si vlastní chleba a hnojil bych vlastníma hovnama. Prý bych to bez lidí nevydržel. Háček je v tom, že já to nejsem schopnej vydržet s lidma. Baví mě je pozorovat a vidět, jak dělaj ve svým životě naprosto debilní rozhodnutí, abych pak šel a zrakvil si koleno nebo utrácel nesmyslný prachy za předražený kafe ve stánku na hnusným poflusaným autobusáku. Život je plnej paradoxů. Co víc si přát než kočky, pár listů papíru a oblaka. Věděl to už Baudelaire. 
Co že jsem to psal o těch půlkách rodiny? No, abych řekl pravdu, je mi jako bych byl přímo mezi těma vrásčitejma tučnejma půlkama. Dost hluboko v prdeli. I rodina jsou jenom lidi. A je to už nějaká doba, co jsem přestal dělat rozdíl kdo jsou ti druzí a kdo je rodina. Vlastně na tom vůbec nezáleží. Nezáleží vůbec na ničem. A když si tyhle věci a lidi člověk nepřipouští příliš k tělu, neměl by problém s roubenkou uprostřed lesa, nebo jenom s lesem, nebo s čímkoliv co je uprostřed ničeho. 
Dozvěděl jsem se nedávno od jedný holky, že jsem odpornej. Našla se v mým textu a myslela si, že i ostatní ji v tom textu najdou. Řekl jsem ji na to, že může být v naprostým klidu, protože jednak moje texty nikdo nečte a druhak je i ona všem úplně u prdele. Navíc jsou to jenom texty. Nejsem v nich nikdy ani já, ani ona a ani nikdo jinej. Není v nich totiž ve skutečnosti vůbec nikdo, i když by klidně mohl být. Nějak to nepochopila. Ale to je ten odstup od věcí a lidí, o kterým jsem mluvil. Když mi říkala, abych chcípnul, že jsem hnusnej a odpornej a že se jí hnusím, viděl jsem v ní najednou jenom všechny ty slova. Byla stejně prázdná, stejně o ničem a já jsem se usmíval. 
A tak si držím odstup. A jestli někoho dokáže naštvat můj text, znamená to jenom, že to s tím mým psaním není ještě úplně v prdeli. A na to se napiju. ` 
    },
    { 
      nazev: 'Proč tady sakra sedím s bejvalou.', 
      text: `No nazdar! Tak se posaď! Jo že už sedíš? Tak fajn. Nedáš si pivo? Říkáš kafe? Jak je libo, já poslední dobou taky moc nepiju. Mám potom chuť pustit plyn a zapálit svíčku. Ale jak se vůbec máš? Ne počkej, mně je to vlastně fuk, nejsem finanční poradce a nejsem ani z těch, co se takhle ptají, protože něco chtějí, protože mají zájem bavit se, protože je zajímá něco úplně jinýho, ale rozhodně jim je u prdele, jak se zrovna máš. Stejně bys kecal a řekl bys mi něco jako „dobře.“ A že tě zajímá, jak jsem na tom já? Ty víš co mi můžeš… Já se mám „dobře“ a budu mít za to, že ty se máš taky tak. Chtělo by to popojet, jenže najednou si nemáme moc co říct, viď? Podlaha je dneska nějaká rovná, zrcadlo nějaký skleněný, porcelán porcelánovej, židle je málo dřevěná a stůl má ještě pořád všechny čtyři nohy, i když se kinklá sem a tam. Počasí je skvělý, pokud teda zrovna nestojí za hovno, co já vím. Koukám, že komunikace je tady dneska na mně. Já mám radši, když jsou za ty mluvící blbce všichni ostatní… Ale jak chceš, povídal jsem ti, co se mi nedávno stalo? 
Říkám si, proč tam sakra sedím. Bar plnej lidí a na záda mi dýchá bejvalá. Taky najednou vypadá mnohem líp, než když to ještě před pár měsíci nebyla moje bejvalá. Jenže to už je takovej věčnej syndrom skupiny ženských, se kterýma měl jeden v minulosti tu čest. Však o tom víš svoje. No a na druhým konci baru sedí nezávisle na mně někdo úplně cizí, ačkoliv je mi v tu chvíli o dost míň cizí, než ta bývalá. Tomu cizímu člověku bych zas ale asi těžko dokázal nacpat ptáka do obličeje, nebo do jiný díry. Ale srát na to.
Lidi kolem se baví a lidi na baru se baví, lidi u stolů se baví. Baví se v sedě i ve stoje a i když jdou na hajzl. Lidi láteří a mluví spolu a smějou se a mají na obličejích masky méněcennosti a já ji mám taky. A má ji i ten otrávenej barman. Na obličeji a na podrážce bot a na prdeli. Viděl bys ji, kdybys otevřel oči. Kdybys mi sundal kalhoty, byla by tam. Pár lidí místo zábavy pracuje. Alespoň to pohledem do firemních počítačů a hlasitým domlouváním někomu, kdo sedí na druhým konci drátu předstírá. Já předstírám, že jsem. Sedím si tam a říkám si, proč sakra? Jsou mi všichni cizí. A je mi cizí i to, co z týhle noci vzejde, až na to dojde koncem večera. Sedím tam v košili, jako mucholapka na oči. Okolapka. Ani nevím, proč mám ten krémovej límeček u krku. Než jsem si sednul v baru, byl jsem na pracovním pohovoru. Možná jsem předpokládal, že udělám dojem. Ale zpětně vzato se to celý zdá jako naprostá hovadina a já se dobrovolně dusím něčím, co bývalo na míru. Ztratil jsem míru. Ztratil jsem soudnost. Ztratil jsem bejvalou a za chvíli nejspíš taky přijdu o peníze. Odcizenej sám sobě a svojí vlastní myšlence, na kterou už jsem stejně zapomněl, zatímco si takhle přemýšlím a civím po místnosti. Okradl jsem se sám. Okradli mě. Okradla mě.
Pořád tam sedí s přísným výrazem ve tváři, mluví s nějakým vlasatým amantem a ohlíží se na mě. Jako kdybych jí vadil, nebo co. Barman se při pohledu na mě zbavuje úsměvu ve prospěch soucitných očí a pak se točí zády ke mně, aby se mohl věnovat svýmu. 
Že se nudíš? To mě fakt mrzí. Ale počkej si, začlo to být taky trochu zajímavý.
Do baru totiž vešla holka s malým bílým kocourem. Hned se zdraví s barmanem a toho nenapadne nic lepšího, než nalít tomu kocourovi do misky místo vody pivo. Kocour se začne motat kolem, poskakuje po baru, nikde se mu to moc nezdá, až skočí na mě a na moji židli. Sedne si mi do klína a kouká na mě jedním žlutým a druhým modrým okem. Nevím na který se mám dívat dřív a tak ho prostě jenom hladím a říkám si, že život vlastně není zas tak špatnej. Najednou ucítím strašnej smrad. Kocour se zvedne a seskočí ze židle. Ten malej zmrd mi v klíně na košili nechal velký mokrý hovno. Prostě mě posral. Teď už se lidi kolem nebaví. Křiví se jim obličeje, od barmana přes bejvalku, která ho už nemůže mít zkřivenější, až po toho vlasatce a jiný cizí lidi. Bar se vylidňuje a já se jdu na záchod zbavit posraný košile. Ten kocour byl ale dobrej, podařilo se mu úplně minout kalhoty. Košilí jsem ucpal záchod a barman mi za odměnu donesl svoje náhradní tričko. Krátkej proces. Kapitola uzavřena. Když jsem se vrátil ze záchoda, všichni kromě barmana byli pryč. Přisedl jsem si k baru a objednal si skotskou na led. Pil jsem sám. Barman čistil whiskovky jako ve filmech, vzduch se pročistil a bylo zase dobře. 
Z toho plyne, že kočky vědí až moc dobře, co člověk potřebuje. A umí mu to dopřát svým vlastním způsobem, i kdyby se z toho měli posrat. Dáš si ještě kafe?` 
    },
    { 
      nazev: 'Malá holka.', 
      text: `Bylo to docela dobrý léto. Tehdy jsem ho trávil na klidným předměstí, u jedný malý blonďatý holky. Jmenovala se Laura. Bydlela pořád ještě u rodičů, ale nepřišlo mi to nijak zvlášť divný, spíš naopak. Její táta byl architekt a na domě to bylo znát. Vypadal totiž jako něco, co by nějakej vysokoškolskej profesor prohlásil za „velké umělecké dílo.“ Sousedi si mezitím ťukali na čelo a přemýšleli, kdo mohl takovou zhovadilost vymyslet, natož postavit. V podstatě to byla přerostlá střecha ukotvená v zemi. Střecha, co má čtyři patra, sklep, asi tak dvacet pokojů, velký vzdušný prostory, ve všech třech koupelnách drahý obklady, na zdech v obýváku samý divný abstraktní obrazy a dveře z masivu od země ke stropu do každý místnosti. Jenže i když by z toho baráku mohl být malej domov důchodců nebo moderně vybavený leprosárium, nikdo jinej v něm vyjma tý holky, její kočky a rodičů nebydlel.
Lauřiny rodiče se měli fakt dobře. Měli se tak dobře, že si mohli dovolit nejdražší dům v ulici a zároveň si mohli dovolit v něm prakticky nebydlet. Váleli se buď u moře nebo na horách, ale každopádně někde hodně daleko. S Laurou jsme to dali dohromady ještě před létem, takže když její rodiče uvolnili prostor, byl ten barák na dva měsíce jenom pro mě, pro ni a pro tu malou strakatou kočku z útulku, která tomu všemu šéfovala. Občas nějakej místní kocour přeběhl přes zahradu, sedl si u bazénu plnýho slaný vody, zkusil se napít a když mu to moc nesedlo, otřepal se a odběhl zase pryč. Ta kočka se na něj jenom letmo podívala a dál se jazykem věnovala svým roztaženým nohám.
Zahradu ohraničovaly vysoký tůje a za nima stálo fotbalový hřiště. Každou neděli dopoledne se tam hráli zápasy dívčího přeboru. Občas jsem sledoval, jak se na těch holkách všechno třese, zatímco se v tom úmorným vedru honí za balonem. Podél hřiště stávalo pár motivovaných tatínků, kteří popíjeli místní mizerný čepovaný pivo a křičeli do hřiště svoje rady a nadávky. Hrával se tam i mužskej fotbal a většinou v něm figurovali ti tatínci. Jenže na ně se nikdo dívat nechodil. Ani jejich manželky, ani jejich dcery. 
Bylo to začátkem června, když jsem zase jednou přišel z města a Laura stála na schodech. V zádech měla okno s odpoledním sluncem. Stála tam jen tak, v kalhotkách. Připadala mi jako stopadesáti centimetrová bohyně s tomu odpovídajícím tělem. Možná byla trochu malá, ale měla všechno, co potřebovala mít. Postavil jsem se na schod pod ní, chytil jsem jí jednou rukou kolem tváře, druhou pod zadkem a dal jsem jí jeden delší polibek. Vzala mě za ruku a táhla mě za sebou do pokoje. Po cestě se byla schopná nějak zbavit i těch kalhotek a pak zbavila oblečení i mě. Spali jsme spolu a zbytek odpoledne nic moc jinýho nedělali. Já byl po práci, po desítkách krátkých rozhovorů s lidma, který jsem nechtěl vidět, natož se s nimi bavit. 
„Dobrý den, dal bych si nějaký kafe“
„A jaký?“ 
„No nějaký dobrý!“
Ona zase chtěla jenom ležet vedle mě. A tak jsme leželi, nic moc neříkali a stálo to za to. Čekali jsme při tom ležení na večer, kdy bude vedro únosnější. Větrák vedle postele občas přihrnul trochu vzduchu k nadechnutí. Potili jsme se jako zvířata a po chvíli jsme se spolu stejně tak znovu vyspali. 
Se zlatou hodinkou se přitoulala i ta malá kočka. Proskočila otevřeným střešním oknem na koberec, přímo doprostřed pokoje. Dvakrát nebo třikrát dlouze zamňoukala a přišla si pro pohlazení. Nechala si to párkrát líbit, ale když jsem ji omrzel, odběhla se najíst dolů do obýváku. Seděl jsem na kraji postele a koukal, jak se ve vzduchu vlní její zdviženej ocas. Laura seděla za mnou a opírala se o mě. Na zádech jsem cítil její bradavky, drobnýma rukama mě hladila na stehnech. Hlavu si položila vedle mojí a začala mě líbat na krku. Zapomněl jsem na všechny kočky světa. Stáhla mě zpátky na postel a já ji oplácel líbání na krku. Pokračoval jsem níž, až jsem se dostal k prsům. Nebyly z největších, ale měly svůj tvar, symetrii a půvab, tak jako celá Laura. Lehce jsem jí zmáčkl bradavky. Čekal jsem nějakou reakci, ale ona jen dál tiše vzdychala. Šel jsem ještě níž, až mi sevřela hlavu mezi stehny a já ji začal lízal. Zprava doleva, nahoru a dolů. Na jazyku jsem cítil pot a spoustu dalších tekutin. Cítil jsem taky trochu sebe, vzhledem k tomu, že už jsem v ní ten den byl, ale nepřestával jsem. Bavilo mě jak se kroutí a zmítá, zatímco mě mají v moci její malý nohy. Kdyby chtěla, klidně mi mohla rozdrtit hlavu, jenže pak by z toho všeho nic moc neměla, leda tak bordel. 
Konečně se udělala a já vylezl na ni, abych ho do ní mohl vrazit. Bylo to jako potápět se v moři. Zatímco jsem do toho bušil, proběhla kolem postele kočka. Zaslechl jsem cinkání obojku. Vyskočila zpátky na okno a zase byla pryč. V tu chvíli jsem se udělal a bylo po všem. Vždycky mě mnohem víc vzrušovalo líbání, nebo když mi to dělala pusou, nebo když jsem jí to mohl pusou dělat já. Když došlo na konvenční přístup, nikdy jsem se moc nebavil a chtěl jsem to mít za sebou co nejrychleji. Kdyby v tu chvíli hráli za domem fotbal, skóre po přestávce by bylo 1:1. A na světě byl vymýcen hlad, nastolen mír a zavládla rovnováha. 
Chvíli jsme zase jenom leželi, až se nakonec zvedla a šla si dát sprchu. Mír skončil. Lidi zase měli hlad a rovnováhu rozstříleli jadernýma hlavicema na sračky. 
„Máš chuť na nějaký ovoce?“ řekla a vykoukla ze dveří, zatímco si přidržovala ručník na hrudníku, i když se nemusela bát, že by ji viděl někdo cizí. Já jsem se taky nebál a koukal jsem se na ní.
„Jedno už jsem si před chvíli dal…“ Usmáli jsme se na sebe. 
„Můžeme si nějaký dát.“ Bez dalších slov sešla dolů do kuchyně a já jsem se šel vychcat. Byl to divnej záchod. Vedly k němu totiž dvoje dveře, jedny na chodbu a druhý do koupelny. Přemýšlel jsem, jestli je ten její táta génius a nebo úplnej imbecil a při tom jsem se v sedě vymočil. Bez umytí rukou jsem vešel do sprchy a pustil vlažnou vodu. Když jsem se utřel, sešel jsem po schodech a sledoval, jak Laura u kuchyňský linky popochází sem a tam a jak jí při tom nadskakuje zadek. Už zase byla v kalhotkách. Víc toho nepotřebovala, možná i to bylo trochu moc. Žasnul jsem nad tím, jak uměla při loupání granátovýho jablka nezasrat celou kuchyň. Žasnul jsem nad další spoustou věcí, který uměla. 
Na hřišti už se nic nehrálo, zato v televizi běžel živý přenos turnaje smíšených bojových umění. Běžně jsme se dívali na seriály nebo filmy. Běžně mě taky zvládla ojet víckrát, než kolik jsme zvládli shlédnout filmů. Tentokrát to ale bylo jiný. Popíjeli jsme suchý bílý víno a krmili se tím vyloupaným granátovým jablkem. Byl jsem jako tureckej sultán a ona byla všech mých třináct manželek. V prvním zápase jeden frajer se zápasovým kontem 4-21 nečekaně prohrál s domácím zápasníkem s bilancí 2-0. Když došlo na zápas těžkých vah, o vítězi jsem měl jasno ve chvíli, kdy se zápasník z modrýho rohu zadýchal už při nástupu do klece. 
Líbilo se mi, jak je do toho sportu nadšená. Nepřišlo mi, že by si na zájem jenom hrála. Pořád se na něco ptala a nebyly to úplně debilní otázky. Připadal jsem si jako průvodce na hradě, když se ho někdo na něco náhodou zeptá. Turnaj trval zhruba do jedný do rána. Kolem půlnoci se vrátila kočka. Okno bylo jenom pootevřený a tak začala mňoukat a čekala, až jí pustím dovnitř. Já jsem ji pustil. Nebylo to poprvý, co jsem jí takhle v noci otevíral okno. Musel jsem vstát. Někdy jenom v trenkách, někdy bez nich. Kočka proběhla kolem a šla se znova nažrat. Tentokrát se ale pak přidala a dívala se na hlavní zápas večera s náma. Welterová váha. Čtyři roky neporažený domácí borec dostával dvě kola hroznou bídu, až do chvíle, kdy Maďarskému vyzivateli došel dech. Ve čtvrtém kole inkasoval Maďar tři kolena do hlavy a klesl k zemi. Vyhrál jsem pětistovku. Vyhrál jsem život.
Ráno jsem se probudil s jednou kočkou na mně a druhou vedle mě… tu jednu jsem ze sebe sundal a tu druhou jsem si přitáhl ještě blíž k sobě. Cítil jsem na sobě její půlky a její půlky musely cítit mě. Čekala na to, až se probudím. Byla po ránu mnohem čilejší než já. Pomalu jsem znovu usínal, ale ona se ke mně otočila, odhrnula peřinu, schoulila se mi k nohám a vzala si mě do pusy. To mě celkem spolehlivě probudilo. Než jsme vstali z postele, kočka byla venku, Laura byla na mě a já byl v ní. 
Tak šel den po dni a já si to užíval. Čas utíkal rychle, jako kdykoliv, když něco konečně stojí za to. Pak začalo padat listí a bylo září. Laura se ode mě nechala nahá fotit na filmovou zrcadlovku a já nechal její kočku, aby mi v noci lezla po břiše a strkala mi řiťku do ksichtu stejně tak, jak jsem to nechal dělat Lauru. Ta kočka měla svojí hlavu. Seděla a koukala na mě, jak si hraju s laserem. Připadal jsem si jako úplnej idiot. Jako kdyby si ona hrála se mnou. Čekala, až se na to vykašlu a hodím ji něco k jídlu, což jsem taky většinou udělal. 
Všechno to bylo až moc jednoduchý a přesně proto mě to pomalu přestávalo bavit. Neexistovalo žádný napětí. Neexistoval spor. Nedokázali jsme se pohádat ani o komunistech, ani o nezvednutým prkýnku. Když vám ten druhej všechno odkýve, časem jakoby tam vůbec nebyl. 
Ten večer, co se její rodiče měli vrátit, jsem stál u okna a Laura přede mnou klečela. Byl jsem už blízko vrcholu a ona dál zrychlovala. Najednou vidím, jak k domu přijíždí auto rodičů. Začal jsem jí pobízet, aby ještě přidala. Auto zastavilo před domem, její máma vystoupila a první pohled směřovala do toho jedinýho okna, který v baráku svítilo. Myslel jsem, že mě musí mít Laura někde v žaludku, jak hluboko jsem byl. Stál jsem v tom okně nahej a naprosto odevzdaneh. Pak jsem se udělal a cítil jsem, jak Lauře do krku pumpuju svojí nálož. Vzdychnul jsem, usmál jsem se a nenapadlo mě nic lepšího, než to celý podpořit zamáváním směrem k mámě. Ta odvrátila pohled a zašla k domu. Nikdy jsem moc dobře neviděl na dálku. Neviděl jsem jí do tváře a doufal jsem, že ona mně taky ne. Na okno přede mě vyskočila kočka, sedla si, podívala se na celou tu scénu a začala mňoukat. Ten večer jsem odjel a protože začala škola, vracel jsem se k Lauře jenom na víkendy. 
	Brzo byly Vánoce a když jsem k ní znovu přijel, všichni byli doma. Vypadalo to na vánoční pohodu z letáku nákupního řetězce. V televizi hráli umělý pořady a umělý pohádky. Obývák byl vyzdobenej světýlkama a v rohu místnosti stál dvoumetrovej smrk. Všichni se usmívali, ale já nějak neměl důvod. Asi za to mohli lidi, co najednou zaplnili město a ulice a já se přes ně v ty dny musel prodírat, abych se vůbec někam dostal. Vlastně se mi během těch několika dní vůbec nechtělo nikam jezdit. Ani za ní. Věděl jsem už za čím a za kým jedu. Bylo to pořád to samý. 
Všude visely samý barvy a hvězdičky a dekorace. Veselý monotónní melodie hráli do zbláznění. Mottem davu se stala nákupní horečka a shon za spokojeností a vánoční pohodou. Kdo z těch lidí měl opravdovou pohodu? Ten kdo jí měl před 24. prosincem jí měl zase po něm a ten kdo jí před tím neměl, neměl ji ani na 24. ani na 25. a ani nikdy jindy. 
To všechno jsem si říkal, když jsem vešel do jejího pokoje. V ruce jsem držel dárek, kterej jsem jí dal a od ní jsem zase jeden dostal. Přišlo mi to zbytečně zbytečný. Pak jsme se zase začali líbat, až jsem skončil pod ní. Přejížděla mi kundou po obličeji a jednou rukou se mi opírala o ptáka. Chutnalo to jinak než normálně a když jsem přidal prsty. uviděl jsem na nich krev. Zastavil jsem jí. Když mě viděla, rozbrečela se a slezla ze mě. Vstal jsem a podíval jsem se do malýho zrcátka, který leželo na komodě vedle postele. Měl jsem na obličeji asi tak litr krve, měl jsem v ní namočený vousy, nos, čelo, obočí, no prostě všechno. Odešel jsem do koupelny a dal jsem si sprchu. Když jsem se vrátil, pořád seděla nahá na posteli a brečela. 
„Nic se neděje“ řekl jsem jí a pohladil jsem jí na rameni. Nepřipadalo mi to nijak nechutný, ale zároveň jsem nic moc necítil. Neměl jsem na nic chuť. Ani na ní, ani na Vánoce. Přestal jsem tam chtít být. A jelikož jsem tam neměl v plánu strávit večer, odešel jsem. Vzal jsem si kabát a když jsme se loučili u hlavních dveří, usmál jsem se na ní. Ona se usmála na mě a já jsem šel.
Na zastávce mě přijíždějící autobus ohodil hnědou sněhovou břečkou. Věděl jsem, že už sem nikdy znovu nepřijedu. Bylo 24. a když jsem konečně přijel domů, zjistil jsem, že jsem si u Laury zapomněl náhradní trenky a dárek, co mi k dala. Shodil jsem ze sebe všechny věci a vlezl jsem do postele. Bylo mi jako bych měl na sobě všechny ty svetry s vánočními vzory, které jsem poslední pár dní viděl. Měl jsem horečku vyvolanou Vánoční horečkou všech ostatních. Prospal jsem večer, noc, ráno a skoro celý další den. Protože jsem mohl. Nezvedal jsem telefon. Neodpovídal jsem na zprávy. Nikdo nic nechtěl, nikdo nic nečekal, protože jsem o nikom nevěděl. 
Druhý den jsem zvedl telefon a zavolal jsem Katce. Taky ho zvedla a zeptala se, jak se mám. Za oknem štěkal pes. ` 
    },
    { 
      nazev: 'Kolejní řád.', 
      text: `Občas se na chodbě z nějakého pokoje ozvalo tlumené vzdychání. Občas bylo slyšet vrzání dveří a kroky mířící na umývárnu a zase zpátky. Sem tam nebylo slyšet vůbec nic. Marek se opřel o dveře, zašmátral do tmy v místě, kde odhadoval kliku, zabral a vešel do pokoje. Jednou rukou se přidržoval stěny, druhou potichu zavřel dveře, aby neprobudil spolubydlícího. Šoural se po podlaze a snažil se do ničeho nenarazit. Všechno se s ním motalo a on netušil, jestli ušel jeden nebo pět metrů. Dlaní se opřel o desku stolu a zkusil jít podél něj. Narazil přitom do židle. Na chvíli se zastavil, slyšel jenom tiché oddychování. Obešel siluetu židle a stanul někde uprostřed pokoje. Najednou se neměl čeho chytit, neměl kolem sebe žádný podpůrný bod. Byl jako tonoucí bez stébla. Byl sám na rozbouřeném moři. A jak se houpal, podlomily se mu nohy. Skončil na podlaze. Nahmatal ale roh postele a podařilo se mu k ní po čtyřech dojít. Slyšel, jak mu z kapsy vypadl svazek klíčů. Náraz klíčů do podlahy zachrastil v tichu pokoje jako shoz vodíkové pumy. Oddychování na pozadí tmy ale pokračovalo. Pomalu se vysápal na kraj postele a posadil se. Promnul si obličej a pravou rukou sáhl po peřině. Do dlaně ale chytil něčí lýtko. Dost svalnaté lýtko. 
	Na protější straně pokoje se rozsvítila lampička. Vedle ní Marek zpozoroval obrys spolubydlícího. Připadal mu tak o deset let mladší než včera. Pak se lýtko pohlo a vedle něj se v šeru objevila další postava s lehce vyděšeným výrazem. Pochopil, že je tu někdo navíc. Chvíli bylo ticho a pak někdo promluvil. Marek si byl jistý jenom tím, že ten kdo mluví není on. 
„Hele kámo, jsi tady správně?“ 
„Jsem.“ Kontroval nekompromisně Marek, taky proto, že nebyl schopný složitější věty. 
„No, to asi nejsi…“ pokračoval hlas. 
	Marka napadlo, že by si s oběma vetřelci snadno poradil. Vzpomněl si, že na svém stole nechal talíř se zbytky jablka a spolu s tím i nůž. Na vteřinu si pohrával s jistou myšlenkou, kterou by někdo upjatý mohl označit za zvrhlost. Marek ale cítil, že na přítomném okamžiku není něco v pořádku. Že jsou na něj zkrátka upřené dva pohledy lidí, kteří jsou tady nejspíš o něco víc doma, než je on. Posral to. Buď byl v blbým baráku, nebo v blbým patře, nebo se sešlo obojí a ještě ke všemu to byl prostě blbej pokoj. Blbej večer, blbý místo, blbej čas. 
	Sunul nohu po podlaze a když uslyšel cinkání klíčů, přihrál si svazek k sobě. Předklonil se, aby klíče zvedl a mohl konečně zmizet. Předklonil se ale moc. Přepadl a skončil zpátky na podlaze. Měl pocit, jako by na něm visely všechny zraky světa. Dokázal to. Klíče byly zase jeho. Je to šampión napříč váhovými kategoriemi. 
Trvalo docela dlouhou chvíli, než se postavil. V šeru zpozoroval kliku a vydal se k ní. Před dveřmi se ohlédl do místnosti, pak odešel a zavřel za sebou. Stál na chodbě a pořád se trochu kymácel. Dali mu zabrat. Klíče, břemeno pozornosti, ta piva co měl v sobě, slova jeho holky. Zády se opřel o dveře. Uslyšel cvaknutí zámku a chlapecké hlasy. Zamknuli zevnitř. Nebyl vítán. A stejně s nimi v místnosti bude až do rána. Neusnou a pokud ano, bude se jim o něm zdát. Budou se o něm bavit. Bude pro ně celým světem. 
	Otočil se a rozepnul si zip na kalhotech. Dlouze se vymočil na dveře. Koukal na svoje dílo. Louže se rozpínala po spárách mezi podlahovými kachličkami. Zapnul se a vyšel na konec chodby, až stanul před schodištěm. Posadil se na nejvrchnější schod. Zase vstoupil do života někomu, aniž by chtěl, aniž by ho zvali a aniž by ho v životě chtěli. Nejspíš to nebylo poprvé a ani naposledy. Schoulil se do klubíčka a usnul. ` 
    },
    { 
      nazev: 'Prší i v noci.', 
      text: `I kapky bubnující o parapet mi dávají najevo, jak moc jsem na dně a jak moc se ještě budu topit. Je zase noc, takže to pro jistotu zmiňuju znova, jelikož jsem o tom nepsal v dostatečným množství všech svých textů. Připadám si jako poslední člověk na planetě a zbývá ještě chvíle před tím, než se opět rozsvítí pouliční lampy. Už bude jenom hůř. Neumím se vyrovnat se svojí životní situací. Ale protože jsem pro teď posledním člověkem na planetě, nikomu nebude vadit, že si tu zase slovně pobrečím.
Budu se ještě chvíli topit, až se stanu rybou, naučím se plavat, naučím se v tom chodit, chodit po dně, poslepu, bez zvuku, bez dechu, klopýtat přes korály a jinej sajrajt. Bez ostychu a bez nutkání se zase vynořit, v podřepu, ve svý nízký přirozenosti a nahotě. Nejlíp ještě do rána vyvedu nějakou hovadinu. Třeba nějaký holce napíšu vyznání. a nebo si budu dělat v nějakým jiným textu srandu z nějaký jiný holky, který jsem dřív vyznání napsal, jenom abych oddálil přiznání, že některý věci už prostě dávno skončily. Nemá smysl se vracet, ale ohlížet se nepřestanu, dokud nezmizím za zatáčkou. 
Nejradši bych usnul. Teď a tady na tom stole, abych se už nikdy nemusel probudit. Už vidím ty titulky.
ZESNUL NEČEKANĚ MEZI STRÁNKAMI PAPÍRU POPSANÝMI NEDOPSANÝM PSANÍM GLOBÁLNÍHO ROZSAHU, KTERÝ MÁ POTENCIÁL NASTOLIT SVĚTOVÝ MÍR A ZAŽEHNAT HLAD V AFRICE.
Vůbec nejradši bych se ale taky zašel podívat na nějaký zápasy. Těžký váhy, střední váhy, pérový váhy. Na tom nezáleží. Zavře se klec a kromě těch dvou borců a stepujícího rozhodčího v sobě zavírá i moje traumata a potřeby a chtíče a úkoly a práci. Jako by nic nebylo. Ještě jsem taky neochutnal jednu značku skotský, kterou jsem ochutnat chtěl a toho kafe... Toho kafe co jsem ještě nevypil. Vždycky mě zajímalo, jestli umí v Demokratické republice Kongo dělat dobrý kafe, alespoň tak dobrý, jak dobrý jsou ve světovým žebříčku chudoby. 
Ale srát na chudobu. Srát na Demokratickou republiku Kongo a na všechny demokratický republiky co nejsou republiky a už vůbec nejsou demokratický. Srát na všechny ostatní státy, co jsou nebo nejsou demokratický a nemají to pro jistotu ani v názvu. Srát na všechny panovníky a na všechno kafe a na whisku a na lidi a na zápasy. Hlavně že píšu a jednou bych chtěl, aby tím taky tak všechno skončilo.` 
    },
    { 
      nazev: 'Tenhle text nemá originální název a ty se s tím budeš muset smířit.', 
      text: `Už jsem vám někdy řekl, že je poezie mrtvá? Já vím že říkal, ale nějak tenhle text začít musí, takže asi takhle:
Občas se mi podaří napsat něco, o čem si myslím, že je originální. Víc než cokoliv jinýho mi tohle přesvědčení dělá jistou osobní tvůrčí radost a taky si můžu připadat důležitě, jako člověk s vlastní hlavou a vlastníma myšlenkama. Většinou ale taky netrvá moc dlouho, než mě nějakej text - nejlíp alespoň padesát let starej - vyvede z omylu. Vtip je v tom, že mým cílem není vytvářet něco novýho a už vůbec si nekladu za cíl cokoliv předávat čtenáři. Nechci ani šířit moudro, který by ještě ke všemu nemuselo být moje. Nechci šířit žádný moudro. Neradím nikomu, jakou rukou se má na záchodě utírat. Neradím nikomu vůbec nic. Nemám potřebu být za člena skupiny „mluvíme a nemáme k tomu co říct” a nechci taky psát, aniž bych nic neříkal, nebo si tak nechci alespoň připadat. Psaní je v tomhle nejspíš ještě horší, než kdybych jenom něco vykládal nahlas. Na většinu řečí se totiž rychle zapomene, zatímco psanej text zůstává napsanej, i když se mine smyslem, obsahem a původní myšlenkou autora. Na druhou stranu - když si tohle nikdo nepřečte, nebude na to mít ani kdo zapomenout. samozřejmě kromě mě. Já už si ale stejně nepamatuju, co jsem sesmolil o pár řádek výš a o čem jsem to vlastně chtěl psát. 
Píšu obrazy a nesnažím se o nic víc. Obrazy jsou to, co chci psaním říkat. spíš než originalitou jsem posedlej samotným psaním. Píšu, protože to prostě potřebuju. Když se přes týden nedostanu k papíru, začínám být nervózní. Když to nedělám, znamená to, že přestávám žít, že se kolem mě přestávají dít věci. Když delší dobu nepíšu, dohání mě to k šílenství, stejně jako mě dohání k šílenství, když nechám odejít krásnou holku, kterou potkám na ulici. Psal bych, i kdybych za to musel bůhví komu platit. Je to jako mít v posteli tu krásnou holku z ulice, nebo jako chodit každej druhej den na zápasy - když to můžu dělat zadarmo, není důvod, abych to taky nedělal. 
Psaní je to určitej proces. Je to bouřka. Jsou to erupce na slunci. Za ťukání do klávesnice umíraj novorozeňata a rozvádí se všechny šťastný manželství. Vzniká písmenko po písmenku, rodí se nový světy a nový vesmíry a nový životy. Taky se zpátky vrací už jednou prožitý situace, i s tím vším balastem a různýma tělesnýma tekutinama. Teče alkohol a hoří svíčky a padají nadávky a jiný stejně zbytečný slova, hýří se vším, co je zrovna po ruce a nikdo nemá tušení, co se děje mezi těma čtyřma stěnama, kde zrovna sedím. 
To platí i na tebe, chlape. Co právě držíš na vodítku psa. Nevidím ti sice do tváře, ale chodit ven se psem v půl třetí ráno může znamenat jenom pár věcí. buď má ten pes sračku a nebo se jako sračka cítíš ty. Každopádně…
Víte proč taky ještě píšu? Dělám to proto, že mě ostatní autoři nebaví. Příliš málo autorů dokázalo vymáčknout ze všedního dne trochu toho nektaru a vměstnat ho do řádek. Nevím jak vás, ale mě nikdy nebavilo sušený ovoce tak, jako čerstvý - to je totiž plný šťávy, plný překvapení, plný energie. Všichni z těch, co uměli tuhle šťávu do svýho psaní dostat, už jsou mrtví. Ve skutečnosti mi někteří mrtví autoři ale připadají díky jejich textům daleko živější, než stále ještě žijící a píšící autoři. Aktuální - zejména - básnickou tvorbu bych pracovně rozdělil do dvou kategorií - mainstream a underground. autoři undergroundu sice sdílí s autory mainstreamu neschopnost napsat dobrou báseň, zato mainstreamoví tvůrci mají díky svému marketingovému umu dosah - čili mají za tu tragédii, kterou produkují, ještě peníze navíc. Naštěstí je tady pořád ještě dílo těch autorů, co žerou prach a tihle autoři už na něm a ani na sobě nedokážou nic pokazit. Budiž jim to přičteno k dobru. Taky je potřeba si říct, že když je něco mrtvý - třeba autoři poezie a s nimi i poezie jako taková - neznamená to, že nemůžeme ještě nějakou dobu chodit na hřbitov a vzpomínat na starý dobrý časy. Budiž to k dobru přičteno nám.

Abych se ale vrátil k úvodu prvního odstavce: největší průser je, když se vám začnou líbit vaše vlastní slova.
Nikomu necpu vlastní vkus nebo preferenci, jenom nemám náladu hledat stejný myšlenky, který nacházím psaný v dnešním a mně blízkým jazyce, taky v dílech renesance a baroka a antiky a bůh ví kde ještě. Než bych se v těch knihách k něčemu dostal, nejspíš bych usnul. Můžete si o mně klidně myslet, že jsem nekulturní barbar, nebo že nerozumím literatuře - vlastně si o mně můžete myslete co chcete, já vás taky zrovna nemiluju - ale viděli jste už někdy někoho, jak přirozeně mluví o kundě, jako o rozkvetlé růžičce s kapičkou ranní rosy na okvětním lístku? Já ne, nejspíš bych s někým takovým nechtěl být moc dlouho v jedný místnosti, ale pokusů o básně, co v sobě mají obdobnou frázi a jsou považovány za vrchol té či oné doby, těch už jsem pár viděl a taky jsem viděl spousta frajerů a frajerek, který se o kundě neuměli vyjádřit vůbec nijak, jenže to už je zase trochu jiný téma a jinej problém.
Proto je poezie mrtvá, zamrzlá v jistý době, kterou symbolicky přežilo jen pár vyvolenců. Nemám vztah k těm všem falešným, na počet slabik odpočítaným slokám. Nemám vztah ani k jejich slovům o neexistujících problémech a situacích a lidech, k jejich autorům a ani ke světu, ve kterém ti autoři žili. Je mi blíž prostitutka procházející se na hlavní třídě, nebo zaplivanej stánek s kafem na nejšpinavějším autobusáku v zemi a vlastně i ten autobusák je mi bližší, než tihle pitomci a jejich připitomělý výtvory. Je mi bližší přečíst si o nepovedeným sexu během jízdy ve výtahu a o fetujících dětech, než o utrpení mladého Werthera. Sebevražda je taky skvělý téma, stejně jako deprese, samota a pití. to, co k tomu bylo potřeba napsat už bylo napsaný. Ale někdo psaní myslí vážně - opravdově - a někdo se o to jenom snaží.
 A to je celý. Kdo hledá, ten najde. Není potřeba, aby pořád vznikaly nový věci. Nový často neznamená dobrý a i když mě starší hudba dohání k nostalgii pro doby, který jsem nemohl zažít, myslím si, že svět nikdy nebyl tak dobrej, aby se někdy dalo mluvit o starých dobrých časech. Všechno má totiž svoje. Dnešek je pořád stejně strašnej, jako byl včerejšek, jenom člověk trpí o něco dýl, díky lékům a prevenci, pokud na ní teda chodí. Včerejšek má ale jednu zásadní výhodu - byl dřív - a díky omezenosti jazyka a slov měl tu příležitost vytvořit něco, co dneska už znovu originálně nejde. Právě proto, milý čtenáři, je poezie - a především ta dobrá - odsouzena ke smrti.` 
    },
    { 
      nazev: 'Myslí to se mnou dobře.', 
      text: `Odkulil se na svojí stranu rozkládacího gauče a koukal do stropu. 
„Mohl by ses jít prosím tě vyčůrat?“
„A proč jako?“
„No, po milování se musí čůrat, jinak si vyměňujeme a přenášíme bakterie, je to nezdravý“
S poraženým úsměvem na tváři se bez dalších proslovů odebral na záchod.
 „A umyj si ruce!“ křičela za ním.
 Už je to tady, pomyslel si.

 PRVOTŘÍDNÍ A SVĚTOZNÁMÝ SPISOVATEL VĚRNĚ ZACHYCUJÍCÍ REALITU VŠEDNÍHO DNE SE PO POHLAVNÍM STYKU VYPRAVUJE NA TOALETU, ABY MOHL PŘEMÝŠLET NAD SVÝM DEKADENTNĚ VEDENÝM ŽIVOTEM, ZATÍMCO S OHLEDUPLNOSTÍ KE SVÉ MILOVANÉ PARTNERCE VYPOUŠTÍ SVÉ ŠKODLIVÉ BAKTERIE, JEJÍ ŠKODLIVÉ BAKTERIE, PIVO, ŽLUČ A TRADIČNÍ HODNOTY STARÝCH DOBRÝCH ČASŮ DO STOK DĚJIN.

Spláchnul a poodešel do kuchyně. Sedl si k jídelnímu stolu a z misky na něm si vzal nazelenalý banán. Na chodbě byly slyšet její kroky. 
„Myslí to se mnou dobře“ dodal polohlasem.` 
    },
    { 
      nazev: 'Špatnej den.', 
      text: `Konečně vyšel na střechu univerzitních kolejí. Posadil se na značně zrezlý zábradlí a nechal nohy volně pohupovat ve vzduchu. Koukal, jak se v mrholení stávají ze střech zrcadla. Podíval se k zemi, na asfaltovou plochu parkoviště. Taky se leskla a on se v ní hodně vzdáleně odrážel, spolu s celou masivní budovou o desítce pater. Na ploše stálo pár ojetých aut a výmoly v asfaltu se pomalu plnily vodou. Stíral si déšť z čela, ale pak ho zarazilo, jak se tři patra pod ním otevřelo jedno z oken. Zrovna teď nebyla chvíle na něčí společnost. Přál si být alespoň na těch pár posledních minut sám, bez diváků. 
Z okna se vyklonilo torzo nějaký holky. Na zlomek vteřiny jí uviděl do obličeje. Byla bledá a oči se jí potápěly hodně hluboko do tváře. Kratší černý vlasy jí poskakovaly ve větru. a potom, jakoby to nic neznamenalo, se přehoupla přes okraj okna a padala k zemi. Bez váhání, bez ptaní, bez křiku a bez možnosti vrátit všechno zpátky. Padala rychle. Rychleji, než si mohl uvědomit, co se vlastně děje. Prostě jenom seděl dál na tom zrezlým zábradlí a ona mu proklouzla mezi prstama. Byla mu v tu chvíli mnohem blíž, než kdokoliv kdy mohl být. Do toho momentu jí nikdy neviděl a ani jí neznal, ale stejně o ní najednou věděl úplně všechno, co bylo podstatný. Byla mu tak blízko i přes to, že stačil jenom jednou mrknout, aby se z ní, z živý holky s černýma vlasama, stala rudá skvrna na asfaltu. Sebrala mu křídla. Sebrala mu všechno odhodlání, který se v něm týdny sbíralo. Sebrala mu všechny iluze a ideály o tom, jak to vypadá, když se někdo vraždí sám. Vzala mu naději na rychlý a osamělý konec a oběma z nich vzala dech. Jí už ho ale na rozdíl od něj nikdo nedokáže vrátit. 
Krev na asfaltu se rozpíjela v dešti a on uslyšel první křik sbíhajících se lidí. Všichni v tu chvíli vypadali stejně a všichni už byly stejně zbytečný. Taky se začaly otevírat další okna pokojů. I ty přestaly dávat smysl. Všechno přestalo dávat smysl. Dávno už se odehrával jinej příběh, on měl ale na očích jenom moment jejího pádu. Sám už se k tomu neměl. Nedokázal jí následovat. Kdyby mohl, udělal by to první, aby ona nemusela, ale teď už bylo pozdě. A kdyby jí znal, dal by smysl jejím dnům a jejímu životu. Byl by to ukázkovej příběh o lásce nad propastí. Doslova. 
Přehoupl se zpátky na střechu a sesunul se k zemi. Moknul a pořád měl před sebou její tvář, kterou dneska viděl poprvý a naposledy, jako poslední ze všech. Nevěděl co s tím faktem počít. Bylo mu to líto a byl na sebe naštvanej. Byl naštvanej na ní, že mu nedala šanci, že si nedala šanci. Zase to nedokázal a už nejspíš nikdy nedokáže. Pomyslel si, že to nikdy nemyslel tak vážně, aby se z něj stala mrtvá holka na mokrým asfaltu. Prohlížel si dlaně na které shůry kapala voda a říkal si, že svět nepotřebuje dalšího živýho člověka. Ale kdo sakra potřebuje další mrtvolu?` 
    },
    { 
      nazev: 'Co dělat bez bot.', 
      text: `Klečel na koberci a hlavu měl vpáčenou mezi stehny holky, kterou byste si tipli na pětadvacet a zároveň na patnáct. Dělal svoji práci a celkem ztěžka se mu dýchalo. Neslyšel ani její slova, ani její vzdychání, což pro něj byla vůbec ta nejlepší část z celýho aktu. Cítil jenom ji, a její ruku, která se mu chvílemi snažila vyrvat vlasy z hlavy. Jenže pak přestal a jako by se ocitl v úplně jiném světě, hlasitě se rozesmál. Stisknutí stehen povolilo a její nohy se rozevřely. Nechápavě se na něj koukala posazená na posteli
„Co je? co dě-láš?“ přeskočil jí hlas. 
„Vzpomněl jsem si na jeden vtip o rybách...“ dostal ze sebe přes smích, přičemž  mu na tváři přistála facka. 
„Ty seš fakt neskutečný hovado!!“ udeřila ho podruhé. 
„Hajzle!“ potřetí už minula, vstala, překročila ho a s řevem odběhla do koupelny, kde se zamkla. Zůstal sám, rozvalený na koberci a pořád se řechtal, až mu z toho začaly slzet oči a jedna strana tváře se mu barvila do ruda. Natáhl se pro jeden z polštářů, který ležel na posteli, utřel si do něj obličej, potom vstal a začal třídit oblečení poházené po podlaze. Nemohl najít svojí druhou ponožku. 
V pokoji zela tma, kterou půlil jenom pruh světla prorážející malou mezeru mezi dvěma černými závěsy. Rozhrnul jeden z nich a pokusil se podívat do ulice. Na první dobrou ho bolestivě oslepilo vycházející slunce. Na druhou dobrou ho rozbolelo všechno ostatní, když uviděl plnou ulici lidí. Jeden zástup mířící tam, druhej zástup jdoucí opačným směrem. Každej za tím svým malým denním cílem. Malým denním ničím. Třetí dobrá už nepřišla. Hrklo v něm a při pohledu na hodiny si uvědomil, že musí do práce. Vypadalo to, že snídani si bude muset sehnat cestou, protože ta holka byla pořád zamčená v koupelně. Bude muset volit mezi hromadou lidí v supermarketu a hladem až do odpoledne, kdy mu směna končí. V práci jíst nemohl a nechtěl tam ani jít. Nechtěl v bytě zůstat. Nechtěl snídat. Nechtěl mezi lidi. Nechtěl už vůbec nic. 
Závěsy nechal roztažené a díky světlu konečně našel i druhou ponožku. Vzal si batoh, odešel z pokoje a zastavil se až u dveří koupelny. Opřel se o ně a poslouchal. Slyšel jenom tekoucí vodu ve sprše. Přemýšlel, jestli by neměl něco říct, ale nakonec zůstal zticha. Šel k hlavním dveřím a než je za sebou zabouchl, ohlédl se. Předpokládal, že je to naposledy, co vidí tuhle chodbu z překližky, co vidí vrzající podlahu, co vidí všechny ty různý trubky vedoucí u stěn a u stropu a mezi topením. Je to naposledy, co vidí okna z mléčnýho skla směřující do vnitrobloku tohohle hnijícího baráku. Konečně se otočil a pomalu zavřel dveře. Vykročil, jenže se hned zase zastavil. Na nohách měl jenom ty svoje dvě bílý smradlavý ponožky, co si pamatovaly včerejšek a hlavně včerejší večer. Boty zůstaly za dveřmi. Zabouchal na ně, ale bez odezvy. Zkusil to znovu, trochu agresivněji, volal a dožadoval se otevření. Možná ho neslyšela, možná nechtěla, každopádně ani další bouchání nepomohlo. Začínal být lehce zoufalý, musel jít, aby stihl otevřít kavárnu. Neměl na výběr. sundal si ty ponožky, hodil je na rohožku před dveře, naposledy poslal proti desce dveří pravý hák a konečně odešel.
Cestou přemýšlel, co bude říkat zákazníkům, až se ho zeptají, proč na sobě nemá boty. Nemohl se celý den schovávat za barem, mohl by se ale vymlouvat na nový trendy zdravý životní styl, nebo ho ještě napadlo říkat, že prohrál sázku, nebo že svoje boty daroval nešťastnému bezdomovci, kterého potkal právě cestou do práce. Mohl říkat, že se mu boty rozpadly a je placený tak málo, že prostě nemá na nové. Ve skutečnosti to byl ale prostě jenom debil. 
Na ulici nikoho ani nenapadlo otáčet se za ním, i když jeho chůze po dlažebních kostkách připomínala tu kačeří. Podařilo se mu vyhnout se všem střepům, žvýkačkám a flekům po opilcích a po psech. Konečně došel ke kavárně. Strčil klíč do zámku, otevřel dveře a hned za sebou zamkl. Byl bez bot, bez ponožek a taky byl hladovej. Ale byl sám.  ` 
    },
    { 
      nazev: 'Taky měl občas nějaký sny.', 
      text: `Vzbudil se zrovna když sluníčko svítilo, kytičky voněly a ptáčci zpívali. 
Myslel na svých sto milionů. Představoval si, jak si je jde konečně vyzvednout, ať už se pro podobný prachy chodí kamkoliv. Taky si představoval, jak má konečně po těch mnoha úmorných letech úsměv na tváři. Představoval si, za co všechno utrácí, jak investuje, staví nemovitost, kupuje letenky z destinace do destinace, daruje na charitu pro nemocné děti, zase investuje, jde do obchodu a dělá normální nákup, aniž by vyhledával slevové akce. Myslel na to, jak jsou všechny jeho životní problémy vyřešené, jak si prostě žije bez starostí a bez ohlížení na svoje aktuálně poloprázdné kapsy.
Všechny představy byly hezky konkrétní. V puse cítil chuť drinku s paraplíčkem a na tvářích ho řezal vánek od severských fjordů. Viděl slunce zapadající do mořské hladiny a taky se mu postavil, ze všech těch holek, který teď začnou jevit zájem. Postavil se mu taky z představy nekonečný samoty. Myslel na to, jak si konečně sedne na verandě, před svojí malou roubenkou, na klíně mu bude usínat kocour a někde uprostřed lesa bude pozorovat pobíhající srnky a divočáky a lišky a mravence a kdoví co ještě. Bude mít domov. A bude mít cokoliv a kdykoliv.
Tak si ležel dál ve svý rozvrzaný posteli, která je pro jednoho moc velká a pro dva moc malá. Myslel na svých sto milionů a poslouchal, jak ptáčci zpívají, cítil, jak kytičky voní, zatímco ho to zkurvený slunce pálilo do očí. Postel totiž před lety postavil přímo pod okna směřující na východ. Neměl na to změnit svoje palčivé životní rozhodnutí. Ta okna byla tím jediným pravým důvodem, pro který ještě stále vstával. Špatně umístěná postel, s nohama k východu. A taky měl občas nějaký sny.` 
    },
    { 
      nazev: 'Malý, nazelenalý, tvrdý a správně kyselý švestky.', 
      text: `Mám rád kyselý švestky a tak si tady teď sedím, s nohama na stole, pojídám si ty malý, nazelenalý, tvrdý a správně kyselý švestky, čímž si krátím čekání na bouřku, která doufám co nevidět přijde. Už se blýská. Bouřky jsou fajn, poslední dobou si taky čím dál víc užívám tmu. Ještě víc, než kdy dřív. Je klid. Všechno je čistý, bez lidí, bez pohybu a zbytečný existence, která jenom zahlcuje ulice a cesty a tak nějak všechno. Když je bouřka, vmísí se do toho potemnělýho klidu smršť zvuků a pohybu a energie. Je tma a je světlo a tma a světlo a mokro. Nejspíš o tom už psala každá druhá spisovatelská nula. Takže tady je bezvýznamnej popis bouřky od jedný další. 
Právě mi došly švestky a zároveň jich mám plný břicho. To jsou mi paradoxy. Ale k čemu jsou mi švestky v břiše? Už z nich nebudu mít nic. Žádnej požitek. Žádná přidaná hodnota. Chuťový pohárky se můžou jít klouzat. Je mi jedno, co z těch švestek bude mít zbytek těla. Teď už je jenom vysrat. To si nejspíš nechám na zítra, nebo na dnešek, už je po půlnoci. Co teď? Měl bych si najít nějakou mužnou zábavu muže s mužně oholenou hrudí. 
Poezie je mrtvá a mě občas zvou básníkem. Nejspíš jsem teda mrtvej, což by mýmu aktuálnímu stavu i docela odpovídalo. Ani se nehnu, ale na to, že jsem mrtvej, vyhrávám celkem slušný peníze na sázkách. Je sobota večer, pořád je skoro třicet stupňů a venku zvučí ten hnusnej hmyz, kterej nikdo nikdy neviděl, ale stejně vydává zvuky. Je všude kolem. 
Souběžně běží čtyři turnaje smíšených bojových umění a já je sleduju, Přepínám mezi zápasama a přicházím o peníze, respektive inkasuju. zrovna se mi povedlo vyhrát trojnásobek ze tří sázek, to když všechny z těch zápasů skončily v podobnej čas. Dva na bodový rozhodnutí a ten třetí úderem kolena do hlavy. Zrovna jsem měl to štěstí vidět tu vraždu živě. Chlápek co padal k zemi se nejspíš cítil podobně jako já, prohrál v první minutě a vypadal dost bezvládně, až mrtvě. Přitom se do zápasu vrhnul s elánem a motivací. To je další podobnost - já taky nemám zrovna velkou motivaci ve věcech pokračovat, když se serou. I za prohru dostal ten zápasník nějaký peníze a já sázel proti němu. Oba mrtvý, oba živý, oba v balíku. Takhle si tu každej den prohrávám. Dokud to tak půjde i s penězma, ještě se tady na to asi nevykašlu úplně. 
Ta  bouřka přišla až v půl třetí. Zápasy skončily a já zůstal dvacet korun v plusu. mám hlad a nemám žádný švestky.` 
    },
    { 
      nazev: 'Kavárenský povalečky.', 
      text: `Občas se mi při práci v kavárně povede natrefit na jistej typ zákaznic. Tyhle ženský chodí do kaváren o samotě, ve větším počtu, s rodinou, s kamarádkama, nebo z donucení s někým, od koho dostali stý pozvání a už jim přišlo blbý ho odmítat. Nic z toho ale není podstatný. Chci teď psát o holkách, který vrhaj protáhlý pohledy s takovou kadencí, že by pro ně našly uplatnění i v armádě. Posílají po nich jenom zlehka potlačovanou touhu po rozhovoru, touhu po vzrušení, a každopádně touhu po tom, abych je po zavíračce, kdy konečně zhasnu světla, zlomil v pase o barovej pult, serval z nich někdy až moc přiléhavý kalhoty a vymrdal z nich všechny vnitřnosti, od prdele po mozek. 
Když jim ke stolu donesu jejich kafe, můžu s klidem zaplout do bezpečí baru. Pak se ze mě stává ten největší tvrďák v místnosti a aby taky ne. Ty holky maj v očích napsaný, že se nosí na nohou s momentálně neomezenou otevírací dobu. Možná za to může osamělost. Možná závidí obsahu nekonečně dlouhý vychloubačný řeči kamarádek. Možná chtějí dát tomu frajerovy najevo, že už ho po dnešku fakt nikdy vidět nechtějí. Co já vím… i v mým výrazu ale můžou cítit příležitost k upuštění trocha frustrace. Nepromluvíme ani slovo, stejně vím, že v danej moment nejsem sám, kdo v místnosti sdílí možnost alternativní reality spočívající ve hře pro dva.
Nakonec dochlastaj svoje kapučíno, dožerou dorty a když mi daj až nápadně vysoký dýško, za bezdůvodnýho chychotu pomalu odcházejí. Zavřou dveře a zpoza výlohy se ještě otočí, přičemž mi věnujou ten nejvyzívavější a nejdelší pohled ze všech. Když nás dělí tenká vrstva skla, mají najednou pocit bezpečí. Potom mi zmizí ze života a většinou už je nikdy neuvidím. Můžu si tak v imaginárním bločku odškrtnout, že jsem se pro jednou zase ovládl. Poslední co zbyde je fantazie. Jenomže i ta vyprchá z hlavy sakra rychle, obzvlášť když se mi do ní v kavárně nasere zrovna příchozí šéfová. Než všechny svoje myšlenky na šukání zaženu, ještě se mi s nechutí vybavuje pár scénářů. Nevím co je hnusnější, jestli varianta, kdyby se šéfový zachtělo zákaznici asistovat, nebo varianta, kdyby se jí zase tolik nechtělo. Těžko říct. 
Nemějte mi za zlý, jaký představy v hlavě chovám. Nakonec jsou to moje představy a vy se svým názorem můžete jít třeba do prdele. A hlavně, nebuďte pokrytci. Moje myšlenkový ženský nejsou jenom chodící kundy z povídek, který si člověk může přečíst v ulepenejch časopisech, nebo na webech, co člověka od čtení odpuzujou nejen obsahem, ale už samotným vzezřením. Vím moc dobře, že moje představy jsou často i v hlavách těch zákaznic. A opět - nemusí o tom ani mluvit, pokud teda nepostrádají talent na převádění představ do praxe. Takže se občas prostě může stát, že ta, která si u vás jeden den dávala kafe, klečí druhej den pod pultem, zatímco ji při tom povzbudivě taháte za vlasy a usmíváte se na lidi procházející za výlohou.` 
    },
    { 
      nazev: 'Zrzky.', 
      text: `když se píše o zrzkách, hned je oheň na střeše. problém spočívá  v tom, že žádnej psací stroj nedokáže zaplanout tak, jako okolí v přítomnosti jedný z nich. neumím napsat text ani s půlkou toho náboje, kterej nosívají v očích. ty bývají modrý, jsou podobný jediný kapce vody, která za rok spadne na sahaře. maj barvu tajících ledovců na islandu, nebo jsou zoufale modrý, jako kůže utonulýho člověka. není nic hezčího, než když se ti vedle jedný takový v přeplněným autobuse rozklepou kolena. cítíš se slabej, ten pocit miluješ a chceš milovat i tu holku.
už se mi něco podobnýho dlouho nestalo, ale některý věci je dobrý si čas od času připomenout, to aby člověk nezapomněl jak se věci mají a jaký to je,  když ho fyzicky ovládne něčí blízkost. je to kvetoucí louka v betonovým moři. jsou to padající třešně do uschlý trávy.
každej přelud ale zmizí, aniž by musel být tvojí součástí. připadáš si polovičatě. a když tě opouští, aniž by si tě všimla, vyrve ti jednu plíci a připraví tě taky o žaludek. ten volnej prostor už umí zpátky zaplnit jenom ona. ona, která se nevrátí. zvládneš tak maximálně zírat na místo, kde jsi ji viděl naposledy, kde ještě před chvílí stála. v duchu a s lítostí máváš tomu odjíždějícímu autobusu, ze kterýho jsi kdoví proč vystoupil. doufáš, že se objeví na druhý straně silnice, jako v nějakým filmu, ale nedává to absolutně žádnou logiku. ` 
    },
    { 
      nazev: 'Z červenýho kruhu.', 
      text: `vždycky mě fascinovaly ty japonský malby a dřevoryty a vůbec ten jejich místní styl. černá a červená na bílý barvě. nikdy si nejsem jistej, jestli ty borovice vystupují z mlhy a nebo se do ní noří. budiž tohle příkladem mojí fascinace. klid a vyrovnanost, ticho křičící z plátna. přelud dokonalosti. když ty obrazy vidím, je to jako bych sunul dlaň po torzu těla a cítil husí kůži. při čtení haiku na všech těch plátnech jsem. cítím petrichor, nával čerstvýho vzduchu do zadýchaný místnosti otevřeným oknem, po letním dešti…` 
    },
    { 
      nazev: 'Tramvajová elegie.', 
      text: `svítilna s potiskem parafy psí zamžourala naposledy pro obroušené traverzy vbité do země. kovový vřískot jí byl odpovědí, to jak tramvaj do noci pěla si, coby dvě kočky do krve se drásající o kocoura, nedbaje ze spaní vzbuzené ulice, ni měsíce kvapícího za mračnou oponu, by poslouchat nemusel. pomžilo a elektrika šine se tmou, kývaje sebou na stranu ze strany. světlušky reflektorů ji stěží předbíhají a opar černoty se co krok za ní uzavírá.
sotva tři živáčci vezou se kamsi do dáli. vzduchem čpí po troše sladkého odér kyselosti a z patiny nejedné sedačky ční vryté podpisy. odkazy po půlnoční kreaci pro příští generaci, zdoben i strop a to od podlahy. umělci nesmírných velikostí dali ruce k dílu. mnohým projel už vůz tento. režimy, lidi, vůdce, i tratě přežil, lhostejný zůstal i k sobě samotnému, což je zde patrno.
zabořen v textilu při aktivitě sedavé, zrakem v blbu, brouzdaje prázdnem vozu, vytržen z půlnočního kolotoče úvah třeskem skla plzeňského o podlahu… podivunehodné stvoření vydávající zvuky člověčího zoufalství v duetu střídané nelidskou lhostejností. i to je tu k mání. a jeden by řekl, že i já mám tu čest být ignorován okolím, o změnu nežádaje, na rozdíl od poety sedícího pár sedaček ode mě. desperátem po soumraku, sotvazletilý, mířím pryč od problémů, aby mě lapili. jednoho dne, konečně snad vyveze mě tahle tramvaj, ze smyčky obratiště.` 
    },
    { 
      nazev: 'Všichni moknou.', 
      text: `nahé cihly oděly krajku podvečera. propadlé rolety protíná nachový pramínek zašlého východu. na rozdíl ode mne, ty zrzky jílové, lidem jsou ku prospěchu, neb na ně nekape. holub mokne, nikdo mu nedal mapu k místu, kde jemu podobní deštík přečkají. kočka mokne a brzy si na někom zhojí rány, černou zdědila srst. pes mokne, co tulák mu podobný též hází oči na kolemjdoucí. radost mají kaluže, jež se vytvoří. rybičky láteří, že vody mají dost a o kus dál, neprší na sahaře. o parapet se rozbila zpozdilá kapka odevší přeháňky. rozbila tím i obláček nesoucí minulost. otevřel jsem oči. bez vidu zdál se být pokoj můj komnatou, až k životu se proberou zbylé smysly, zase se budu zdát jako bezdomovec. yesmen–desperát, ovečka k ostříhání. kdyby se každý bod, jenž na stropě prodělal mé zírání, stal vzduchoprázdnem, neměl bych strop. nestalo by se nic neskutečného. třeba lásky nějak hojně mizí a samospádem voda teče. jídlo není na talíři, ani v žaludku. a svět? život? bytí? to bych pohledal.` 
    },
    { 
      nazev: 'Lidská bytost na K.', 
      text: `po jaře minulém, hnízdo vězí na stromě a o kousek výš, pytlík z igelitu. první žluťásek – bohatství z bakelitu – se mezi něčím, co listem buku bylo, snese, kam vítr nese chudobu, na koleni přistane mi.
málo housenek urodilo se, rok co rok, pak letos vysmíváni v líce, a oligarcha v žlutém fraku létajíce do soumraku zase zmizí. bez úroků, nároku na důchod, dětí ve vaku či prostě jen zapomenutých myšlenek, jež v noci sužují, a jedinců co pokoj nedají ani ve dne. jednou takovou lidskou bytostí, nenechán v náruč skal, kde věčně uchován chtěl jsem zůstati. toť společné s tím motýlem je míti mi, leč scházejí mi křídla, nárok na rozmyšlenou po vzlétnutí. 
víra v důvody a dospělost co v obličeji hledá vrásky marně. toť ona zachránkyně, či důvod plané zkázy? podléhá každý té, bez ohledu na smysl, na přání, na nesnázi. svěřit se, je jako mluvit s kostkou čísel, od jedné do šesti. trojka hozena, zdá se býti dvím, jalové ve zlatě či achát z rukou překupníka. dlím v pochybě, zda nabídnuté ruky vzdáti se, přejít ji bez povšimnutí… či uchopit a tahat doufaje, že se neocitne tam, kde já bývaje, nebylo hezky. 
sotva objektem, jen mnohou z tváří človíčka, „hezká,“ jeden odplivne si. a s touhou těkavou, čekám na cíl debaty o sobeckosti. sluníčko chodící a zakrnělý úsměv snad i v komatu. nevěřím, či věřiti se nechce? přesto zpověď vedu. o jednu oběť víc než tu neslavnou nulu, pojmou zřejmě má milá úbočí. do obličeje slzy u rakve derou se, v davu, co leč pozdě, přeci se „zajímal“ a kol jich jedna, co odmítnutou paži podává ztěžklou a přeci drží dál.` 
    },
    { 
      nazev: 'Oxymoron bytí.', 
      text: `jak jen to říci, že já – protimluv – pachtiv se v díži rozbředlého sebe sama, vlastně vůbec nemám tucha, tedy netuším nic, až na „pochybuji.“ vyčítání počíná činem minuvším přítomnost a pak se mi divte, že jsem takový. pokaždé jiný, leč jsem to já, snažící se zavděčit, pomoci, dvě tři věty říci, odmlčet se a nezapadnout, pouze padat v nicotu noci, temnot peřin a myšlenek o nenotnosti žití svého, bdít jako ranní mrtvola. a jako ta pak hnitím kazit výrazy obecenstva, co se svou nevinou připlete do mých cest.
ač tělo člověka, podpovrchní vlastnosti jaksi rozličné od onoho druhu. poddruhem živočicha, jenž dá jen na skořápku – tak proto stále jsem tu, nerozlousknutý. jakpak kutálet se světem a stále ze svahu, když pod ním čeká kámen, jistě tvrdší, než má hlava, nátura? a recept neznám. za toliko dvacet let. co je však těch v pusté historii? co jeden je v davu? ztroskotalá minulost, prázdno v čase. a jeden a jedna v davu jsou dva, z čehož pak vzcházejí tři, někdy čtyři, když je na nájem. vychovat, osamět, nechat se okrást a za úmlčné si zubní protézu obstarat, pokud se dožijí. to že je podstata? že možno hledat jinde? absurdita nosí se namísto významu místní prezence. 
přejde to, bylo mi slýchati. že po noci je den a jasno po mlze. pak jest tím příběhem jen zřít záda osoby řkoucí zatracení, jako školačka po defloraci vidí amanta. bez vysvětlení.
není mi pomoci, jsem oxymoron bytí.` 
    },
    { 
      nazev: 'Prší.', 
      text: `z lidu déšť konečně skápl božskou. krčíce se, neb mu to gumová záda dovolují, mizí v kapucích značkových, jež vůkol ceně brzy promoknou, v pasážích domů, za mřížemi bran. 
skryté tváře v křeči, úmoru z vlhkého počasí a snad i z nálady, že práce nevynáší, že duch boží se vznáší jaksi jinde, nežli nad hlavou zdejší, tomu, či onomu příslušící.
stěžují si těm co poslouchají, ač není kdo by naslouchal. takže nesmutní lid, jen v zátiší pochoduje po topících se hlavách kočičích, jež po nocích vlčí a nalhává si slunce mezi mraky a správnost úsudku a vtip důvtipu a užitek záměru a nalhává si o rok více v blahobytu a o pár let vůbec a nalhává si život po smrti a nalhává si, nalhává si, nalhává si bytí při přežívání.
já už si nenalhávám, jen čekám na ránu z milosti. ` 
    },
    { 
      nazev: 'Den po dni dětí.', 
      text: `den po dni dětí a zúčtování dobrých časů. po rozkvětu kapes, hnití charakteru. 
účetní v taláru klade otázky, dychtivý odpovědí. výpovědí dáme vědět, že vina nelpí na našich bedrech, snad na bedru toho druhého, jenž po našem boku na lavici obžalovaných svá bedra maže si voltarenem. 
obhájci s obžalobou mění lež za lež nevýhodnou směnkou, sami přesvědčují se o opaku, to kvůli pocitu z výhry. v síni to jen hřmí a strany tasí těžké kalibry argumentů, důkazy bez důkazu, kryjí si vlastní zadky. diváci se baví nad cizím neštěstím, nad cizí hloupostí, při vší své plytkosti, nepřipouští si, že by si jednou mohli vyměnit sedačky. 
výsledek nejasný. 
mezitím doma, v prázdném ovzduší, houpe se na stranu ze strany, při klice od koupelny, čísi upřímná hlava. ` 
    },
    { 
      nazev: 'Svět se změnil.', 
      text: `svévlastní dějiny ve svazku se zkušeností plodí ideje, jež nakonec ústí mě k činům. myšlenky beze slov byly by pouhou neznámou, v leč možno bohaté, ba abstraktní cizině, kde se jako prázdné džbány po sešlostech póvl slov bez činu povaluje a kde čin, jemuž schází myšlenka, stal se jen nástrojem ku slepému přežívání na den ze dne. nechci dvakrát převracet už jednou přečtený list, ale jednou, naposledy, ohlédnout se nutno je mi. zavřít oči, semknout rty, drtit zuby mezi dásněmi a vzpomínky vybavit si, na dny kdy malichernost zvolena za vládkyni byla.
vše započato velkým písmenem s koncem v bodě tečky, jež málo místa zabere, ale mnohé znamená. kdo by stál o život končící otazníkem? obsahy závěrů jen po formě liší se a zánik v čase není vyhnutelný, to na stať je možné, ba nutné se ptát. než se tedy někdo otáže nahlas, já odpovím.
svět se změnil a je to snad jedna, možná dvě kopy týdnů, co místo dne a noci na nebesích hvězda s lunou svádějí hru o nadvládu a nikdo nevítězí. osa času kreslí minulost a mraky na obloze ustavičně plynou po směru větru, jen já se cítím být žulovým kamínkem vhozeným do proudu, jenž jeho vlivem erozí ztrácí.
poněkud lživá jsou však slova předchozí, neboť se zeměkoule točí stále stejným směrem a rychlostí, jen křiklavé „já“ vybledlo a barvy v tubách vyschly. verše staly se pro mne svůdnou novinkou s tóny sépie a pod jejich břemenem jsem začal vnímat bytí poněkud odlišně. první věty pod mojí rukou, tuhou s odstínem antracitu psané, zašklebily se barevně, minimálně na rozdíl ode mě, měly svou tvář. navzdory kráse listů v posledním tažení, přes snové tužby barev lesa při podzimu však verši prosvítají myšlenky s vidinou mrtvosti téhož posléze. mají téměř jednoho, pro mě známého původce. těžko ale popisuje se něco, co vidět není, natož pak slyšet, cítit… něco co je mou součástí, více než vlastností, nebo rýhou v líci, na první pohled přesto neznatelné.
a tak se sám vypravuji ponurou krajinou k vrcholkům kopců, odkud všechny své problémy zřím z nadhledu, nikoliv zkresleně. z šedého horizontu vidět je nejlépe rozdíl mezi černou a bílou, barev zde netřeba. nač se přemáhat, domýšlet si duhu, tam kde mlha vězí a bouře se chystá…
byl jsem přinucen okolnostmi vzniknuvšími v tikajícím polorozpadu kořenů lidského bytí vidět šerosvitem a ač ne barvoslepý, zbytek pigmentu života na písmo použiv, píši tyto řádky. ` 
    },
    { 
      nazev: 'Klub svésmrtníků', 
      text: `není na tom nic poetického. 
udušení, přelomení kostí, rozmačkání, přetržení končetin a vazu, rozdrcení lebky. kusy mozku tekoucí po stropě a zdi, zvratků plný jícen a plíce, přetékající vana světlé, ještě horké, pomalu chladnoucí krve. blednoucí rozpůlené torzo na pražci s vyděšeným výrazem ve tváři hlásající pozdní rozmyšlení. dveře zaseknuté o namodralý trup visící na klice. policisté dávající světu na odiv své obsahy střev, doktoři budící se ze snů, rodiče následující čin po vzoru svých potomků. odpovědní zoufalí, nevěda si rady s pocitem viny. bušící pěsti do stěny a slzy na tvářích „milujících“ osob.
slabosti a síly onen čin nepostrádá, sobeckosti je plný, od pachatele přes viníky až po důvody. 
chorá mysl, bolest duše a těla. místo motivu vraždy, motiv sebevraždy a podobnost slov není čistě náhodná, vždyť vražda jako vražda, vražda jako sebevražda. odplata těm, kteří bolest působili, pomsta sama sobě. 
následuje krátká zpráva v regionálních plátcích a odsouzení radikálního řešení radikálně smýšlejícími, co ač neznají bytí v kůži svésmrtníka, jistě došli by k smíru jinými způsoby a znají recepty. pracovní tábory, fyzické trestání a „za našich mladých let“ často je slýchati.
uvolnění místa, vzduchu a prostoru, nepřekážení. vzetí vlastního života poprvé a naposledy do svých ruk. ulehčení si pro nezáruku žití života. bolest v časové přímce přenesena do jednoho bodu, vzniknuvší úsečka.
vini jsou všichni a každý z nás nejvíce. toť pozvánka do klubu svésmrtníků.` 
    },
    { 
      nazev: 'Poslední list', 
      text: `pokud hledíte na tyto řádky, již je pozdě. moje nohy tnou vzduch a dechu už mi nejspíš pomnoho nezbývá. než i ten poslední zbyteček, zapomněná zásoba živůtka z těla vyprchá a já za sebou konečně dveře zavřu, dovolím si ještě naposledy vyjádřit se, odkázat poslední slova, rozloučit se, říci nashledanou.
ponoukám vám tímto mými texty, leč nedokončenými, jednosměrnou jízdenku do mého já, vysvětlení všeho toho humbuku a nepřátelství uplynulých několika mála dní. ačkoli se to může z některých řádek zdát, nepřijímám roli oběti, ni roli soudce, neboť mi nepřísluší. jsem podatelna příběhu a soudy jsou patrně na vás, či na někom, něčem vyšším. 
moje jméno se těmito okamžiky stává statistikou, tělo odejde v popel či prach a má životní hra skončí na posledním řádku textu, lince času, jako bezvýznamná nitka nicu táhnoucí se mimo dějiště jevin, jeviště dějin. 
dříve jsem to nebyl já, kdo dnes dovedl mě ke srázu. snad bych ani to zítřejší „já“ s tím dnešním srovnat nedokázal, ale žádné zítra už přes dnešek nenastane, ne pro mne, ne pro vás, ne pro nikoho. svět zanikne s mým vnímáním a co se stane pak, je jen otázkou nalezení, pochopení a výkladu mých řádek. 
teď už jen zavřu oči a ptačí zpěv utichne, utichá, utichl. ` 
    }
  ];