window.prozaData = [
  {
      nazev: "Co dělat bez bot.",
      podnadpis: "Próza",
      text: `Klečel na koberci a hlavu měl vpáčenou mezi stehny holky, kterou byste si tipli na pětadvacet a zároveň na patnáct. Dělal svoji práci a celkem ztěžka se mu dýchalo. Neslyšel ani její slova, ani její vzdychání, což pro něj byla vůbec ta nejlepší část z celýho aktu. Cítil jenom ji, a její ruku, která se mu chvílemi snažila vyrvat vlasy z hlavy. Jenže pak přestal a jako by se ocitl v úplně jiném světě, hlasitě se rozesmál. Stisknutí stehen povolilo a její nohy se rozevřely. Nechápavě se na něj koukala posazená na posteli
„Co je? co dě-láš?“ přeskočil jí hlas.
„Vzpomněl jsem si na jeden vtip o rybách...“ dostal ze sebe přes smích, přičemž mu na tváři přistála facka.
„Ty seš fakt neskutečný hovado!!“ udeřila ho podruhé.
„Hajzle!“ potřetí už minula, vstala, překročila ho a s řevem odběhla do koupelny, kde se zamkla. Zůstal sám, rozvalený na koberci a pořád se řechtal, až mu z toho začaly slzet oči a jedna strana tváře se mu barvila do ruda. Natáhl se pro jeden z polštářů, který ležel na posteli, utřel si do něj obličej, potom vstal a začal třídit oblečení poházené po podlaze. Nemohl najít svojí druhou ponožku.
V pokoji zela tma, kterou půlil jenom pruh světla prorážející malou mezeru mezi dvěma černými závěsy. Rozhrnul jeden z nich a pokusil se podívat do ulice. Na první dobrou ho bolestivě oslepilo vycházející slunce. Na druhou dobrou ho rozbolelo všechno ostatní, když uviděl plnou ulici lidí. Jeden zástup mířící tam, druhej zástup jdoucí opačným směrem. Každej za tím svým malým denním cílem. Malým denním ničím. Třetí dobrá už nepřišla. Hrklo v něm a při pohledu na hodiny si uvědomil, že musí do práce. Vypadalo to, že snídani si bude muset sehnat cestou, protože ta holka byla pořád zamčená v koupelně. Bude muset volit mezi hromadou lidí v supermarketu a hladem až do odpoledne, kdy mu směna končí. V práci jíst nemohl a nechtěl tam ani jít. Nechtěl v bytě zůstat. Nechtěl snídat. Nechtěl mezi lidi. Nechtěl už vůbec nic.
Závěsy nechal roztažené a díky světlu konečně našel i druhou ponožku. Vzal si batoh, odešel z pokoje a zastavil se až u dveří koupelny. Opřel se o ně a poslouchal. Slyšel jenom tekoucí vodu ve sprše. Přemýšlel, jestli by neměl něco říct, ale nakonec zůstal zticha. Šel k hlavním dveřím a než je za sebou zabouchl, ohlédl se. Předpokládal, že je to naposledy, co vidí tuhle chodbu z překližky, co vidí vrzající podlahu, co vidí všechny ty různý trubky vedoucí u stěn a u stropu a mezi topením. Je to naposledy, co vidí okna z mléčnýho skla směřující do vnitrobloku tohohle hnijícího baráku. Konečně se otočil a pomalu zavřel dveře. Vykročil, jenže se hned zase zastavil. Na nohách měl jenom ty svoje dvě bílý smradlavý ponožky, co si pamatovaly včerejšek a hlavně včerejší večer. Boty zůstaly za dveřmi. Zabouchal na ně, ale bez odezvy. Zkusil to znovu, trochu agresivněji, volal a dožadoval se otevření. Možná ho neslyšela, možná nechtěla, každopádně ani další bouchání nepomohlo. Začínal být lehce zoufalý, musel jít, aby stihl otevřít kavárnu. Neměl na výběr. sundal si ty ponožky, hodil je na rohožku před dveře, naposledy poslal proti desce dveří pravý hák a konečně odešel.
Cestou přemýšlel, co bude říkat zákazníkům, až se ho zeptají, proč na sobě nemá boty. Nemohl se celý den schovávat za barem, mohl by se ale vymlouvat na nový trendy zdravý životní styl, nebo ho ještě napadlo říkat, že prohrál sázku, nebo že svoje boty daroval nešťastnému bezdomovci, kterého potkal právě cestou do práce. Mohl říkat, že se mu boty rozpadly a je placený tak málo, že prostě nema na nové. Ve skutečnosti to byl ale prostě jenom debil.
Na ulici nikoho ani nenapadlo otáčet se za ním, i když jeho chůze po dlažebních kostkách připomínala tu kačeří. Podařilo se mu vyhnout se všem střepům, žvýkačkám a flekům po opilcích a po psech. Konečně došel ke kavárně. Strčil klíč do zámku, otevřel dveře a hned za sebou zamkl. Byl bez bot, bez ponožek a taky byl hladovej. Ale byl sám.`
  }
];